// I've Been There - Data
// 250 countries/territories (UN recognized + commonly listed territories)
// Organized by continent

const COUNTRIES = [
  // Africa (54)
  { name: "Algeria", code: "DZ", continent: "Africa" },
  { name: "Angola", code: "AO", continent: "Africa" },
  { name: "Benin", code: "BJ", continent: "Africa" },
  { name: "Botswana", code: "BW", continent: "Africa" },
  { name: "Burkina Faso", code: "BF", continent: "Africa" },
  { name: "Burundi", code: "BI", continent: "Africa" },
  { name: "Cabo Verde", code: "CV", continent: "Africa" },
  { name: "Cameroon", code: "CM", continent: "Africa" },
  { name: "Central African Republic", code: "CF", continent: "Africa" },
  { name: "Chad", code: "TD", continent: "Africa" },
  { name: "Comoros", code: "KM", continent: "Africa" },
  { name: "Congo (Brazzaville)", code: "CG", continent: "Africa" },
  { name: "Congo (Kinshasa)", code: "CD", continent: "Africa" },
  { name: "Côte d'Ivoire", code: "CI", continent: "Africa" },
  { name: "Djibouti", code: "DJ", continent: "Africa" },
  { name: "Egypt", code: "EG", continent: "Africa" },
  { name: "Equatorial Guinea", code: "GQ", continent: "Africa" },
  { name: "Eritrea", code: "ER", continent: "Africa" },
  { name: "Eswatini", code: "SZ", continent: "Africa" },
  { name: "Ethiopia", code: "ET", continent: "Africa" },
  { name: "Gabon", code: "GA", continent: "Africa" },
  { name: "Gambia", code: "GM", continent: "Africa" },
  { name: "Ghana", code: "GH", continent: "Africa" },
  { name: "Guinea", code: "GN", continent: "Africa" },
  { name: "Guinea-Bissau", code: "GW", continent: "Africa" },
  { name: "Kenya", code: "KE", continent: "Africa" },
  { name: "Lesotho", code: "LS", continent: "Africa" },
  { name: "Liberia", code: "LR", continent: "Africa" },
  { name: "Libya", code: "LY", continent: "Africa" },
  { name: "Madagascar", code: "MG", continent: "Africa" },
  { name: "Malawi", code: "MW", continent: "Africa" },
  { name: "Mali", code: "ML", continent: "Africa" },
  { name: "Mauritania", code: "MR", continent: "Africa" },
  { name: "Mauritius", code: "MU", continent: "Africa" },
  { name: "Morocco", code: "MA", continent: "Africa" },
  { name: "Mozambique", code: "MZ", continent: "Africa" },
  { name: "Namibia", code: "NA", continent: "Africa" },
  { name: "Niger", code: "NE", continent: "Africa" },
  { name: "Nigeria", code: "NG", continent: "Africa" },
  { name: "Rwanda", code: "RW", continent: "Africa" },
  { name: "São Tomé and Príncipe", code: "ST", continent: "Africa" },
  { name: "Senegal", code: "SN", continent: "Africa" },
  { name: "Seychelles", code: "SC", continent: "Africa" },
  { name: "Sierra Leone", code: "SL", continent: "Africa" },
  { name: "Somalia", code: "SO", continent: "Africa" },
  { name: "South Africa", code: "ZA", continent: "Africa" },
  { name: "South Sudan", code: "SS", continent: "Africa" },
  { name: "Sudan", code: "SD", continent: "Africa" },
  { name: "Tanzania", code: "TZ", continent: "Africa" },
  { name: "Togo", code: "TG", continent: "Africa" },
  { name: "Tunisia", code: "TN", continent: "Africa" },
  { name: "Uganda", code: "UG", continent: "Africa" },
  { name: "Zambia", code: "ZM", continent: "Africa" },
  { name: "Zimbabwe", code: "ZW", continent: "Africa" },

  // Asia (49)
  { name: "Afghanistan", code: "AF", continent: "Asia" },
  { name: "Armenia", code: "AM", continent: "Asia" },
  { name: "Azerbaijan", code: "AZ", continent: "Asia" },
  { name: "Bahrain", code: "BH", continent: "Asia" },
  { name: "Bangladesh", code: "BD", continent: "Asia" },
  { name: "Bhutan", code: "BT", continent: "Asia" },
  { name: "Brunei", code: "BN", continent: "Asia" },
  { name: "Cambodia", code: "KH", continent: "Asia" },
  { name: "China", code: "CN", continent: "Asia" },
  { name: "Cyprus", code: "CY", continent: "Asia" },
  { name: "Georgia", code: "GE", continent: "Asia" },
  { name: "India", code: "IN", continent: "Asia" },
  { name: "Indonesia", code: "ID", continent: "Asia" },
  { name: "Iran", code: "IR", continent: "Asia" },
  { name: "Iraq", code: "IQ", continent: "Asia" },
  { name: "Israel", code: "IL", continent: "Asia" },
  { name: "Japan", code: "JP", continent: "Asia" },
  { name: "Jordan", code: "JO", continent: "Asia" },
  { name: "Kazakhstan", code: "KZ", continent: "Asia" },
  { name: "Kuwait", code: "KW", continent: "Asia" },
  { name: "Kyrgyzstan", code: "KG", continent: "Asia" },
  { name: "Laos", code: "LA", continent: "Asia" },
  { name: "Lebanon", code: "LB", continent: "Asia" },
  { name: "Malaysia", code: "MY", continent: "Asia" },
  { name: "Maldives", code: "MV", continent: "Asia" },
  { name: "Mongolia", code: "MN", continent: "Asia" },
  { name: "Myanmar", code: "MM", continent: "Asia" },
  { name: "Nepal", code: "NP", continent: "Asia" },
  { name: "North Korea", code: "KP", continent: "Asia" },
  { name: "Oman", code: "OM", continent: "Asia" },
  { name: "Pakistan", code: "PK", continent: "Asia" },
  { name: "Palestine", code: "PS", continent: "Asia" },
  { name: "Philippines", code: "PH", continent: "Asia" },
  { name: "Qatar", code: "QA", continent: "Asia" },
  { name: "Saudi Arabia", code: "SA", continent: "Asia" },
  { name: "Singapore", code: "SG", continent: "Asia" },
  { name: "South Korea", code: "KR", continent: "Asia" },
  { name: "Sri Lanka", code: "LK", continent: "Asia" },
  { name: "Syria", code: "SY", continent: "Asia" },
  { name: "Taiwan", code: "TW", continent: "Asia" },
  { name: "Tajikistan", code: "TJ", continent: "Asia" },
  { name: "Thailand", code: "TH", continent: "Asia" },
  { name: "Timor-Leste", code: "TL", continent: "Asia" },
  { name: "Turkey", code: "TR", continent: "Asia" },
  { name: "Turkmenistan", code: "TM", continent: "Asia" },
  { name: "United Arab Emirates", code: "AE", continent: "Asia" },
  { name: "Uzbekistan", code: "UZ", continent: "Asia" },
  { name: "Vietnam", code: "VN", continent: "Asia" },
  { name: "Yemen", code: "YE", continent: "Asia" },

  // Europe (44)
  { name: "Albania", code: "AL", continent: "Europe" },
  { name: "Andorra", code: "AD", continent: "Europe" },
  { name: "Austria", code: "AT", continent: "Europe" },
  { name: "Belarus", code: "BY", continent: "Europe" },
  { name: "Belgium", code: "BE", continent: "Europe" },
  { name: "Bosnia and Herzegovina", code: "BA", continent: "Europe" },
  { name: "Bulgaria", code: "BG", continent: "Europe" },
  { name: "Croatia", code: "HR", continent: "Europe" },
  { name: "Czech Republic", code: "CZ", continent: "Europe" },
  { name: "Denmark", code: "DK", continent: "Europe" },
  { name: "Estonia", code: "EE", continent: "Europe" },
  { name: "Finland", code: "FI", continent: "Europe" },
  { name: "France", code: "FR", continent: "Europe" },
  { name: "Germany", code: "DE", continent: "Europe" },
  { name: "Greece", code: "GR", continent: "Europe" },
  { name: "Hungary", code: "HU", continent: "Europe" },
  { name: "Iceland", code: "IS", continent: "Europe" },
  { name: "Ireland", code: "IE", continent: "Europe" },
  { name: "Italy", code: "IT", continent: "Europe" },
  { name: "Kosovo", code: "XK", continent: "Europe" },
  { name: "Latvia", code: "LV", continent: "Europe" },
  { name: "Liechtenstein", code: "LI", continent: "Europe" },
  { name: "Lithuania", code: "LT", continent: "Europe" },
  { name: "Luxembourg", code: "LU", continent: "Europe" },
  { name: "Malta", code: "MT", continent: "Europe" },
  { name: "Moldova", code: "MD", continent: "Europe" },
  { name: "Monaco", code: "MC", continent: "Europe" },
  { name: "Montenegro", code: "ME", continent: "Europe" },
  { name: "Netherlands", code: "NL", continent: "Europe" },
  { name: "North Macedonia", code: "MK", continent: "Europe" },
  { name: "Norway", code: "NO", continent: "Europe" },
  { name: "Poland", code: "PL", continent: "Europe" },
  { name: "Portugal", code: "PT", continent: "Europe" },
  { name: "Romania", code: "RO", continent: "Europe" },
  { name: "Russia", code: "RU", continent: "Europe" },
  { name: "San Marino", code: "SM", continent: "Europe" },
  { name: "Serbia", code: "RS", continent: "Europe" },
  { name: "Slovakia", code: "SK", continent: "Europe" },
  { name: "Slovenia", code: "SI", continent: "Europe" },
  { name: "Spain", code: "ES", continent: "Europe" },
  { name: "Sweden", code: "SE", continent: "Europe" },
  { name: "Switzerland", code: "CH", continent: "Europe" },
  { name: "Ukraine", code: "UA", continent: "Europe" },
  { name: "England", code: "GB-ENG", continent: "Europe" },
  { name: "Scotland", code: "GB-SCT", continent: "Europe" },
  { name: "Wales", code: "GB-WLS", continent: "Europe" },
  { name: "Northern Ireland", code: "GB-NIR", continent: "Europe" },
  { name: "Vatican City", code: "VA", continent: "Europe" },

  // North America (23)
  { name: "Antigua and Barbuda", code: "AG", continent: "North America" },
  { name: "Bahamas", code: "BS", continent: "North America" },
  { name: "Barbados", code: "BB", continent: "North America" },
  { name: "Belize", code: "BZ", continent: "North America" },
  { name: "Canada", code: "CA", continent: "North America" },
  { name: "Costa Rica", code: "CR", continent: "North America" },
  { name: "Cuba", code: "CU", continent: "North America" },
  { name: "Dominica", code: "DM", continent: "North America" },
  { name: "Dominican Republic", code: "DO", continent: "North America" },
  { name: "El Salvador", code: "SV", continent: "North America" },
  { name: "Grenada", code: "GD", continent: "North America" },
  { name: "Guatemala", code: "GT", continent: "North America" },
  { name: "Haiti", code: "HT", continent: "North America" },
  { name: "Honduras", code: "HN", continent: "North America" },
  { name: "Jamaica", code: "JM", continent: "North America" },
  { name: "Mexico", code: "MX", continent: "North America" },
  { name: "Nicaragua", code: "NI", continent: "North America" },
  { name: "Panama", code: "PA", continent: "North America" },
  { name: "Saint Kitts and Nevis", code: "KN", continent: "North America" },
  { name: "Saint Lucia", code: "LC", continent: "North America" },
  { name: "Saint Vincent and the Grenadines", code: "VC", continent: "North America" },
  { name: "Trinidad and Tobago", code: "TT", continent: "North America" },
  { name: "United States", code: "US", continent: "North America" },

  // South America (12)
  { name: "Argentina", code: "AR", continent: "South America" },
  { name: "Bolivia", code: "BO", continent: "South America" },
  { name: "Brazil", code: "BR", continent: "South America" },
  { name: "Chile", code: "CL", continent: "South America" },
  { name: "Colombia", code: "CO", continent: "South America" },
  { name: "Ecuador", code: "EC", continent: "South America" },
  { name: "Guyana", code: "GY", continent: "South America" },
  { name: "Paraguay", code: "PY", continent: "South America" },
  { name: "Peru", code: "PE", continent: "South America" },
  { name: "Suriname", code: "SR", continent: "South America" },
  { name: "Uruguay", code: "UY", continent: "South America" },
  { name: "Venezuela", code: "VE", continent: "South America" },

  // Oceania (14)
  { name: "Australia", code: "AU", continent: "Oceania" },
  { name: "Fiji", code: "FJ", continent: "Oceania" },
  { name: "Kiribati", code: "KI", continent: "Oceania" },
  { name: "Marshall Islands", code: "MH", continent: "Oceania" },
  { name: "Micronesia", code: "FM", continent: "Oceania" },
  { name: "Nauru", code: "NR", continent: "Oceania" },
  { name: "New Zealand", code: "NZ", continent: "Oceania" },
  { name: "Palau", code: "PW", continent: "Oceania" },
  { name: "Papua New Guinea", code: "PG", continent: "Oceania" },
  { name: "Samoa", code: "WS", continent: "Oceania" },
  { name: "Solomon Islands", code: "SB", continent: "Oceania" },
  { name: "Tonga", code: "TO", continent: "Oceania" },
  { name: "Tuvalu", code: "TV", continent: "Oceania" },
  { name: "Vanuatu", code: "VU", continent: "Oceania" },

  // Antarctica (0 sovereign nations, but include the continent marker)
];

// Additional territories to reach ~250 (commonly tracked)
const TERRITORIES = [
  { name: "Hong Kong", code: "HK", continent: "Asia" },
  { name: "Macau", code: "MO", continent: "Asia" },
  { name: "Puerto Rico", code: "PR", continent: "North America" },
  { name: "U.S. Virgin Islands", code: "VI", continent: "North America" },
  { name: "British Virgin Islands", code: "VG", continent: "North America" },
  { name: "Bermuda", code: "BM", continent: "North America" },
  { name: "Cayman Islands", code: "KY", continent: "North America" },
  { name: "Turks and Caicos Islands", code: "TC", continent: "North America" },
  { name: "Aruba", code: "AW", continent: "North America" },
  { name: "Curaçao", code: "CW", continent: "North America" },
  { name: "Sint Maarten", code: "SX", continent: "North America" },
  { name: "Greenland", code: "GL", continent: "North America" },
  { name: "French Guiana", code: "GF", continent: "South America" },
  { name: "Falkland Islands", code: "FK", continent: "South America" },
  { name: "Gibraltar", code: "GI", continent: "Europe" },
  { name: "Faroe Islands", code: "FO", continent: "Europe" },
  { name: "Isle of Man", code: "IM", continent: "Europe" },
  { name: "Jersey", code: "JE", continent: "Europe" },
  { name: "Guernsey", code: "GG", continent: "Europe" },
  { name: "Réunion", code: "RE", continent: "Africa" },
  { name: "Mayotte", code: "YT", continent: "Africa" },
  { name: "Western Sahara", code: "EH", continent: "Africa" },
  { name: "French Polynesia", code: "PF", continent: "Oceania" },
  { name: "New Caledonia", code: "NC", continent: "Oceania" },
  { name: "Guam", code: "GU", continent: "Oceania" },
  { name: "American Samoa", code: "AS", continent: "Oceania" },
  { name: "Northern Mariana Islands", code: "MP", continent: "Oceania" },
  { name: "Cook Islands", code: "CK", continent: "Oceania" },
  { name: "Niue", code: "NU", continent: "Oceania" },
  { name: "Tokelau", code: "TK", continent: "Oceania" },
  { name: "Wallis and Futuna", code: "WF", continent: "Oceania" },
  { name: "Pitcairn Islands", code: "PN", continent: "Oceania" },
  { name: "Norfolk Island", code: "NF", continent: "Oceania" },
  { name: "Christmas Island", code: "CX", continent: "Oceania" },
  { name: "Cocos (Keeling) Islands", code: "CC", continent: "Oceania" },
  { name: "Svalbard", code: "SJ", continent: "Europe" },
  { name: "Åland Islands", code: "AX", continent: "Europe" },
  { name: "Saint Helena", code: "SH", continent: "Africa" },
  { name: "South Georgia", code: "GS", continent: "Antarctica" },
  { name: "French Southern Territories", code: "TF", continent: "Antarctica" },
  { name: "Bouvet Island", code: "BV", continent: "Antarctica" },
  { name: "Heard Island", code: "HM", continent: "Antarctica" },
  { name: "Antarctica", code: "AQ", continent: "Antarctica" },
  { name: "Saint Pierre and Miquelon", code: "PM", continent: "North America" },
  { name: "Montserrat", code: "MS", continent: "North America" },
  { name: "Anguilla", code: "AI", continent: "North America" },
  { name: "Saint Barthélemy", code: "BL", continent: "North America" },
  { name: "Saint Martin", code: "MF", continent: "North America" },
  { name: "Bonaire", code: "BQ", continent: "North America" },
  { name: "Martinique", code: "MQ", continent: "North America" },
  { name: "Guadeloupe", code: "GP", continent: "North America" },
  { name: "British Indian Ocean Territory", code: "IO", continent: "Asia" },
  { name: "South Ossetia", code: "XO", continent: "Asia" },
  { name: "Abkhazia", code: "XA", continent: "Asia" },
  { name: "Somaliland", code: "XS", continent: "Africa" },
];

// Combine all into single list
const ALL_COUNTRIES = [...COUNTRIES, ...TERRITORIES];

// US States (50)
const US_STATES = [
  { name: "Alabama", code: "AL" },
  { name: "Alaska", code: "AK" },
  { name: "Arizona", code: "AZ" },
  { name: "Arkansas", code: "AR" },
  { name: "California", code: "CA" },
  { name: "Colorado", code: "CO" },
  { name: "Connecticut", code: "CT" },
  { name: "Delaware", code: "DE" },
  { name: "Florida", code: "FL" },
  { name: "Georgia", code: "GA" },
  { name: "Hawaii", code: "HI" },
  { name: "Idaho", code: "ID" },
  { name: "Illinois", code: "IL" },
  { name: "Indiana", code: "IN" },
  { name: "Iowa", code: "IA" },
  { name: "Kansas", code: "KS" },
  { name: "Kentucky", code: "KY" },
  { name: "Louisiana", code: "LA" },
  { name: "Maine", code: "ME" },
  { name: "Maryland", code: "MD" },
  { name: "Massachusetts", code: "MA" },
  { name: "Michigan", code: "MI" },
  { name: "Minnesota", code: "MN" },
  { name: "Mississippi", code: "MS" },
  { name: "Missouri", code: "MO" },
  { name: "Montana", code: "MT" },
  { name: "Nebraska", code: "NE" },
  { name: "Nevada", code: "NV" },
  { name: "New Hampshire", code: "NH" },
  { name: "New Jersey", code: "NJ" },
  { name: "New Mexico", code: "NM" },
  { name: "New York", code: "NY" },
  { name: "North Carolina", code: "NC" },
  { name: "North Dakota", code: "ND" },
  { name: "Ohio", code: "OH" },
  { name: "Oklahoma", code: "OK" },
  { name: "Oregon", code: "OR" },
  { name: "Pennsylvania", code: "PA" },
  { name: "Rhode Island", code: "RI" },
  { name: "South Carolina", code: "SC" },
  { name: "South Dakota", code: "SD" },
  { name: "Tennessee", code: "TN" },
  { name: "Texas", code: "TX" },
  { name: "Utah", code: "UT" },
  { name: "Vermont", code: "VT" },
  { name: "Virginia", code: "VA" },
  { name: "Washington", code: "WA" },
  { name: "West Virginia", code: "WV" },
  { name: "Wisconsin", code: "WI" },
  { name: "Wyoming", code: "WY" }
];

// UK Counties (86 ceremonial counties)
const UK_COUNTIES = [
  // England (48)
  { name: "Bedfordshire", country: "England" },
  { name: "Berkshire", country: "England" },
  { name: "Bristol", country: "England" },
  { name: "Buckinghamshire", country: "England" },
  { name: "Cambridgeshire", country: "England" },
  { name: "Cheshire", country: "England" },
  { name: "City of London", country: "England" },
  { name: "Cornwall", country: "England" },
  { name: "Cumbria", country: "England" },
  { name: "Derbyshire", country: "England" },
  { name: "Devon", country: "England" },
  { name: "Dorset", country: "England" },
  { name: "Durham", country: "England" },
  { name: "East Riding of Yorkshire", country: "England" },
  { name: "East Sussex", country: "England" },
  { name: "Essex", country: "England" },
  { name: "Gloucestershire", country: "England" },
  { name: "Greater London", country: "England" },
  { name: "Greater Manchester", country: "England" },
  { name: "Hampshire", country: "England" },
  { name: "Herefordshire", country: "England" },
  { name: "Hertfordshire", country: "England" },
  { name: "Isle of Wight", country: "England" },
  { name: "Kent", country: "England" },
  { name: "Lancashire", country: "England" },
  { name: "Leicestershire", country: "England" },
  { name: "Lincolnshire", country: "England" },
  { name: "Merseyside", country: "England" },
  { name: "Norfolk", country: "England" },
  { name: "North Yorkshire", country: "England" },
  { name: "Northamptonshire", country: "England" },
  { name: "Northumberland", country: "England" },
  { name: "Nottinghamshire", country: "England" },
  { name: "Oxfordshire", country: "England" },
  { name: "Rutland", country: "England" },
  { name: "Shropshire", country: "England" },
  { name: "Somerset", country: "England" },
  { name: "South Yorkshire", country: "England" },
  { name: "Staffordshire", country: "England" },
  { name: "Suffolk", country: "England" },
  { name: "Surrey", country: "England" },
  { name: "Tyne and Wear", country: "England" },
  { name: "Warwickshire", country: "England" },
  { name: "West Midlands", country: "England" },
  { name: "West Sussex", country: "England" },
  { name: "West Yorkshire", country: "England" },
  { name: "Wiltshire", country: "England" },
  { name: "Worcestershire", country: "England" },
  // Scotland (33 council areas grouped as regions)
  { name: "Aberdeenshire", country: "Scotland" },
  { name: "Angus", country: "Scotland" },
  { name: "Argyll and Bute", country: "Scotland" },
  { name: "Ayrshire", country: "Scotland" },
  { name: "Borders", country: "Scotland" },
  { name: "Clackmannanshire", country: "Scotland" },
  { name: "Dumfries and Galloway", country: "Scotland" },
  { name: "Dunbartonshire", country: "Scotland" },
  { name: "Dundee", country: "Scotland" },
  { name: "Edinburgh", country: "Scotland" },
  { name: "Fife", country: "Scotland" },
  { name: "Glasgow", country: "Scotland" },
  { name: "Highland", country: "Scotland" },
  { name: "Inverclyde", country: "Scotland" },
  { name: "Lanarkshire", country: "Scotland" },
  { name: "Lothian", country: "Scotland" },
  { name: "Moray", country: "Scotland" },
  { name: "Orkney", country: "Scotland" },
  { name: "Perth and Kinross", country: "Scotland" },
  { name: "Renfrewshire", country: "Scotland" },
  { name: "Shetland", country: "Scotland" },
  { name: "Stirlingshire", country: "Scotland" },
  { name: "Western Isles", country: "Scotland" },
  // Wales (8 preserved counties)
  { name: "Clwyd", country: "Wales" },
  { name: "Dyfed", country: "Wales" },
  { name: "Gwent", country: "Wales" },
  { name: "Gwynedd", country: "Wales" },
  { name: "Mid Glamorgan", country: "Wales" },
  { name: "Powys", country: "Wales" },
  { name: "South Glamorgan", country: "Wales" },
  { name: "West Glamorgan", country: "Wales" },
  // Northern Ireland (6 traditional counties)
  { name: "Antrim", country: "Northern Ireland" },
  { name: "Armagh", country: "Northern Ireland" },
  { name: "Down", country: "Northern Ireland" },
  { name: "Fermanagh", country: "Northern Ireland" },
  { name: "Londonderry", country: "Northern Ireland" },
  { name: "Tyrone", country: "Northern Ireland" }
];
