// ─── Hawkbology: Initial match data parsed from Futbology CSV ─────────────────
// Format: { date, stadium, home, away, homeScore, awayScore, attendance, competition, notes }
const INITIAL_MATCHES = [
  { date:"2026-05-02", stadium:"Priestfield Stadium", home:"Gillingham FC", away:"Shrewsbury Town", homeScore:1, awayScore:0, attendance:null, competition:"League Two" },
  { date:"2026-04-14", stadium:"Wembley Stadium", home:"England (W)", away:"Spain (W)", homeScore:1, awayScore:0, attendance:null, competition:"Women's World Championship Qualification" },
  { date:"2026-04-06", stadium:"Brisbane Road", home:"Leyton Orient", away:"Huddersfield Town", homeScore:1, awayScore:2, attendance:null, competition:"League One" },
  { date:"2026-04-01", stadium:"Stamford Bridge", home:"Chelsea FC Women", away:"Arsenal Women FC", homeScore:1, awayScore:0, attendance:null, competition:"UEFA Women's Champions League Quarter Final" },
  { date:"2026-03-21", stadium:"Emirates Stadium", home:"Arsenal Women FC", away:"West Ham United Women", homeScore:5, awayScore:0, attendance:null, competition:"Women's Super League" },
  { date:"2026-03-21", stadium:"Coles Park Stadium", home:"Haringey Borough", away:"Winslow United", homeScore:2, awayScore:1, attendance:null, competition:"Spartan South Midlands Premier Division" },
  { date:"2026-03-16", stadium:"Academy Stadium", home:"Manchester City U21", away:"Liverpool FC U21", homeScore:2, awayScore:0, attendance:null, competition:"Premier League 2" },
  { date:"2026-03-14", stadium:"Skye Direct Stadium", home:"Golcar United", away:"Penistone Church FC", homeScore:2, awayScore:0, attendance:null, competition:"Northern Counties East Premier Division" },
  { date:"2026-03-11", stadium:"The Hawthorns", home:"West Bromwich Albion", away:"Southampton FC", homeScore:1, awayScore:1, attendance:null, competition:"Championship" },
  { date:"2026-03-09", stadium:"London Stadium", home:"West Ham United", away:"Brentford FC", homeScore:2, awayScore:2, attendance:null, competition:"FA Cup" },
  { date:"2026-03-07", stadium:"Stadium MK", home:"Milton Keynes Dons", away:"Harrogate Town", homeScore:4, awayScore:1, attendance:null, competition:"League Two" },
  { date:"2026-02-21", stadium:"London Stadium", home:"West Ham United", away:"AFC Bournemouth", homeScore:0, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2026-02-08", stadium:"Emirates Stadium", home:"Arsenal Women FC", away:"Manchester City Women", homeScore:1, awayScore:0, attendance:null, competition:"Women's Super League" },
  { date:"2026-02-07", stadium:"Jack Carter Centre 3G", home:"Frenford FC", away:"Benfleet FC", homeScore:2, awayScore:5, attendance:null, competition:"Essex Senior Football League" },
  { date:"2026-01-30", stadium:"Ashton Gate", home:"Bristol City", away:"Derby County", homeScore:0, awayScore:5, attendance:null, competition:"Championship" },
  { date:"2026-01-28", stadium:"Gtech Community Stadium", home:"Corinthians Feminino", away:"Gotham FC", homeScore:1, awayScore:0, attendance:null, competition:"Women's Champions Cup Semi Final" },
  { date:"2026-01-28", stadium:"Gtech Community Stadium", home:"Arsenal Women FC", away:"AS FAR", homeScore:6, awayScore:0, attendance:null, competition:"Women's Champions Cup Semi Final" },
  { date:"2026-01-17", stadium:"Parsloes Park 3G", home:"Waltham Forest Borough", away:"Woodford Town U23", homeScore:1, awayScore:1, attendance:null, competition:"Essex Saturday Premier Cup" },
  { date:"2026-01-17", stadium:"Parsloes Park 3G", home:"Athletic Newham FC", away:"Little Oakley", homeScore:1, awayScore:1, attendance:null, competition:"Essex Senior Football League" },
  { date:"2026-01-11", stadium:"Brisbane Road", home:"Tottenham Hotspur Women", away:"Leicester City Women", homeScore:1, awayScore:0, attendance:null, competition:"Women's Super League" },
  { date:"2026-01-11", stadium:"London Stadium", home:"West Ham United", away:"Queens Park Rangers", homeScore:2, awayScore:1, attendance:null, competition:"FA Cup" },
  { date:"2026-01-10", stadium:"Hill Dickinson Stadium", home:"Everton FC", away:"Sunderland AFC", homeScore:1, awayScore:1, attendance:null, competition:"FA Cup" },
  { date:"2025-12-29", stadium:"Melbourne Stadium", home:"Chelmsford City", away:"Dagenham and Redbridge", homeScore:1, awayScore:4, attendance:null, competition:"National League South" },
  { date:"2025-12-27", stadium:"Wombwell Recreation Ground", home:"Wombwell Town", away:"Golcar United", homeScore:1, awayScore:1, attendance:null, competition:"Northern Counties East Premier Division" },
  { date:"2025-12-26", stadium:"John Smith's Stadium", home:"Huddersfield Town", away:"Port Vale", homeScore:5, awayScore:0, attendance:null, competition:"League One" },
  { date:"2025-12-06", stadium:"Melbourne Stadium", home:"Chelmsford City", away:"Weston-super-Mare AFC", homeScore:0, awayScore:2, attendance:null, competition:"FA Cup" },
  { date:"2025-11-29", stadium:"Wembley Stadium", home:"England (W)", away:"China (W)", homeScore:8, awayScore:0, attendance:null, competition:"Friendly" },
  { date:"2025-11-09", stadium:"Victoria Road (Dagenham)", home:"West Ham United Women", away:"Leicester City Women", homeScore:1, awayScore:1, attendance:null, competition:"Women's Super League" },
  { date:"2025-11-08", stadium:"Emirates Stadium", home:"Arsenal Women FC", away:"Chelsea FC Women", homeScore:1, awayScore:1, attendance:null, competition:"Women's Super League" },
  { date:"2025-11-08", stadium:"Old Spotted Dog Ground", home:"Clapton CFC", away:"FC Baresi", homeScore:2, awayScore:2, attendance:null, competition:"Eastern Counties League First Division South" },
  { date:"2025-11-01", stadium:"Melbourne Stadium", home:"Chelmsford City", away:"Braintree Town", homeScore:4, awayScore:1, attendance:null, competition:"FA Cup" },
  { date:"2025-10-18", stadium:"Barrows Farm Stadium", home:"Harlow Town FC", away:"Potton United", homeScore:2, awayScore:1, attendance:null, competition:"Spartan South Midlands Premier Division" },
  { date:"2025-10-04", stadium:"Vicarage Road", home:"Watford FC", away:"Oxford United", homeScore:2, awayScore:1, attendance:null, competition:"Championship" },
  { date:"2025-10-01", stadium:"Roding Lane", home:"Buckhurst Hill FC", away:"Romford FC", homeScore:1, awayScore:4, attendance:null, competition:"Essex Senior Football League" },
  { date:"2025-09-30", stadium:"Coles Park Stadium", home:"Haringey Borough", away:"Colney Heath FC", homeScore:1, awayScore:0, attendance:null, competition:"Spartan South Midlands Premier Division" },
  { date:"2025-09-27", stadium:"Emirates Stadium", home:"Arsenal Women FC", away:"Aston Villa Women", homeScore:1, awayScore:1, attendance:null, competition:"Women's Super League" },
  { date:"2025-09-24", stadium:"Tottenham Hotspur Stadium", home:"Tottenham Hotspur", away:"Doncaster Rovers", homeScore:3, awayScore:0, attendance:null, competition:"EFL Cup" },
  { date:"2025-09-17", stadium:"Ashton Athletic Track", home:"Woodford Town FC", away:"Bury Town FC", homeScore:1, awayScore:0, attendance:null, competition:"FA Cup" },
  { date:"2025-09-13", stadium:"Melbourne Stadium", home:"Chelmsford City", away:"Hertford Town", homeScore:6, awayScore:0, attendance:null, competition:"FA Cup" },
  { date:"2025-09-09", stadium:"Capershotts", home:"Waltham Abbey FC", away:"Witham Town FC", homeScore:2, awayScore:1, attendance:null, competition:"Isthmian League North Division" },
  { date:"2025-09-04", stadium:"Europa Point Stadium", home:"Gibraltar", away:"Albania", homeScore:0, awayScore:1, attendance:null, competition:"Friendly" },
  { date:"2025-08-31", stadium:"Craven Cottage", home:"Fulham FC Women", away:"Norwich City Women", homeScore:4, awayScore:2, attendance:null, competition:"Women's National League Division One South East" },
  { date:"2025-08-30", stadium:"Kingsmeadow Stadium", home:"Chelsea FC Women", away:"AC Milan Femminile", homeScore:4, awayScore:1, attendance:null, competition:"Friendly" },
  { date:"2025-08-30", stadium:"Grand Drive", home:"Raynes Park Vale", away:"Ashford United", homeScore:0, awayScore:2, attendance:null, competition:"FA Cup" },
  { date:"2025-08-26", stadium:"Old Spotted Dog Ground", home:"Clapton CFC", away:"Romford FC", homeScore:1, awayScore:3, attendance:null, competition:"Essex Senior Cup" },
  { date:"2025-08-25", stadium:"Reynolds Field", home:"Hanwell Town", away:"Berkhamsted FC", homeScore:1, awayScore:1, attendance:null, competition:"Southern League Premier Division South" },
  { date:"2025-08-23", stadium:"Champion Hill Stadium", home:"Dulwich Hamlet FC", away:"Canvey Island FC", homeScore:2, awayScore:0, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2025-08-20", stadium:"Ashton Athletic Track", home:"Woodford Town FC", away:"Harlow Town FC", homeScore:3, awayScore:2, attendance:null, competition:"FA Cup" },
  { date:"2025-08-19", stadium:"Reynolds Field", home:"Hanwell Town", away:"Brentford FC CC", homeScore:3, awayScore:0, attendance:null, competition:"London Senior Cup Final" },
  { date:"2025-08-16", stadium:"Reynolds Field", home:"Hanwell Town", away:"Yate Town FC", homeScore:3, awayScore:0, attendance:null, competition:"Southern League Premier Division South" },
  { date:"2025-08-09", stadium:"Capershotts", home:"Waltham Abbey FC", away:"Felixstowe & Walton United", homeScore:1, awayScore:0, attendance:null, competition:"Isthmian League North Division" },
  { date:"2025-08-06", stadium:"Mile End Stadium", home:"Sporting Bengal United", away:"Erith Town FC", homeScore:2, awayScore:4, attendance:null, competition:"FA Cup" },
  { date:"2025-08-02", stadium:"Cheshunt Stadium", home:"Cheshunt FC", away:"Royston Town FC", homeScore:2, awayScore:2, attendance:null, competition:"Friendly" },
  { date:"2025-07-30", stadium:"Roding Lane", home:"Buckhurst Hill FC", away:"Soul Tower Hamlets FC", homeScore:2, awayScore:2, attendance:null, competition:"Essex Senior Football League" },
  { date:"2025-07-29", stadium:"Coles Park Stadium", home:"Haringey Borough", away:"Kings Langley FC", homeScore:2, awayScore:1, attendance:null, competition:"Spartan South Midlands Premier Division" },
  { date:"2025-07-27", stadium:"Imperial Fields 3G", home:"AFC Wimbledon Women", away:"Loughborough Lightning Women", homeScore:1, awayScore:2, attendance:null, competition:"Friendly" },
  { date:"2025-07-26", stadium:"Reynolds Field", home:"Hanwell Town", away:"Slough Town FC", homeScore:1, awayScore:4, attendance:null, competition:"Friendly" },
  { date:"2025-07-20", stadium:"The Bees Stadium", home:"London Bees", away:"AFC Wimbledon Women", homeScore:0, awayScore:2, attendance:null, competition:"Friendly" },
  { date:"2025-07-19", stadium:"Gander Green Lane", home:"Sutton United", away:"AFC Wimbledon", homeScore:2, awayScore:0, attendance:null, competition:"Friendly" },
  { date:"2025-07-16", stadium:"Roding Lane", home:"Buckhurst Hill FC", away:"Tilbury FC", homeScore:3, awayScore:2, attendance:null, competition:"" },
  { date:"2025-07-05", stadium:"Oakside Stadium", home:"Clapton CFC", away:"Lymore Gardens", homeScore:3, awayScore:1, attendance:null, competition:"Friendly" },
  { date:"2025-07-04", stadium:"Stade de Genève", home:"Denmark (W)", away:"Sweden (W)", homeScore:0, awayScore:1, attendance:null, competition:"UEFA Women's Euro Group Stage" },
  { date:"2025-07-03", stadium:"Stadion Wankdorf", home:"Spain (W)", away:"Portugal (W)", homeScore:5, awayScore:0, attendance:null, competition:"UEFA Women's Euro Group Stage" },
  { date:"2025-07-02", stadium:"Stockhorn Arena", home:"Iceland (W)", away:"Finland (W)", homeScore:0, awayScore:1, attendance:null, competition:"UEFA Women's Euro Group Stage" },
  { date:"2025-06-01", stadium:"Wembley Stadium", home:"Oldham Athletic", away:"Southend United", homeScore:3, awayScore:2, attendance:null, competition:"National League Play-off Final" },
  { date:"2025-05-30", stadium:"Wembley Stadium", home:"England (W)", away:"Portugal (W)", homeScore:6, awayScore:0, attendance:null, competition:"UEFA Women's Nations League League A" },
  { date:"2025-05-26", stadium:"Wembley Stadium", home:"AFC Wimbledon", away:"Walsall FC", homeScore:1, awayScore:0, attendance:null, competition:"League Two Playoff Final" },
  { date:"2025-05-25", stadium:"St. James' Park", home:"Newcastle United", away:"Everton FC", homeScore:0, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2025-05-19", stadium:"Gtech Community Stadium", home:"Brentford FC B", away:"Tottenham Hotspur U21", homeScore:6, awayScore:1, attendance:null, competition:"Robert Rowan Invitational" },
  { date:"2025-04-26", stadium:"AAMI Park", home:"Melbourne City FC", away:"Adelaide United FC", homeScore:0, awayScore:0, attendance:null, competition:"A-League" },
  { date:"2025-04-23", stadium:"Mohammed Bin Zayed Stadium", home:"Al Jazira", away:"Al Ittihad Kalba", homeScore:1, awayScore:2, attendance:null, competition:"UAE Pro League" },
  { date:"2025-04-19", stadium:"Emirates Stadium", home:"Arsenal Women FC", away:"OL Lyonnes", homeScore:1, awayScore:2, attendance:null, competition:"UEFA Women's Champions League Semi Final" },
  { date:"2025-04-18", stadium:"Ashton Athletic Track", home:"Woodford Town FC", away:"Hullbridge Sports", homeScore:4, awayScore:0, attendance:null, competition:"Essex Senior Football League" },
  { date:"2025-04-18", stadium:"Parkside (Aveley)", home:"Aveley FC", away:"Chelmsford City", homeScore:1, awayScore:0, attendance:null, competition:"National League South" },
  { date:"2025-04-15", stadium:"Reynolds Field", home:"Hanwell Town", away:"Dulwich Hamlet FC", homeScore:3, awayScore:2, attendance:null, competition:"London Senior Cup Semi Final" },
  { date:"2025-04-12", stadium:"Pirelli Stadium", home:"Burton Albion", away:"Huddersfield Town", homeScore:3, awayScore:0, attendance:null, competition:"League One" },
  { date:"2025-04-02", stadium:"Roding Lane", home:"Buckhurst Hill FC", away:"White Ensign FC", homeScore:1, awayScore:0, attendance:null, competition:"Essex Senior Football League" },
  { date:"2025-03-29", stadium:"MBi Shay Stadium", home:"FC Halifax Town", away:"Hartlepool United", homeScore:0, awayScore:1, attendance:null, competition:"National League" },
  { date:"2025-03-27", stadium:"Stamford Bridge", home:"Chelsea FC Women", away:"Manchester City Women", homeScore:3, awayScore:0, attendance:null, competition:"UEFA Women's Champions League Quarter Final" },
  { date:"2025-03-25", stadium:"Reynolds Field", home:"Hanwell Town", away:"Tooting & Mitcham United FC", homeScore:1, awayScore:0, attendance:null, competition:"London Senior Cup" },
  { date:"2025-03-22", stadium:"Roding Lane", home:"Buckhurst Hill FC", away:"Hullbridge Sports", homeScore:1, awayScore:1, attendance:null, competition:"Essex Senior Football League" },
  { date:"2025-03-15", stadium:"The Artic Stadium", home:"Cray Valley Paper Mills", away:"Dover Athletic", homeScore:2, awayScore:1, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2025-03-10", stadium:"London Stadium", home:"West Ham United", away:"Newcastle United", homeScore:0, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2025-03-08", stadium:"Memorial Stadium", home:"Bristol Rovers", away:"Huddersfield Town", homeScore:1, awayScore:0, attendance:null, competition:"League One" },
  { date:"2025-03-05", stadium:"Victoria Road (Dagenham)", home:"West Ham United Women", away:"Manchester City Women", homeScore:1, awayScore:1, attendance:null, competition:"Women's Super League" },
  { date:"2025-03-04", stadium:"Reynolds Field", home:"Hanwell Town", away:"Dorchester Town", homeScore:3, awayScore:0, attendance:null, competition:"Southern League Premier Division South" },
  { date:"2025-03-01", stadium:"Lamex Stadium", home:"Stevenage FC", away:"Huddersfield Town", homeScore:1, awayScore:2, attendance:null, competition:"League One" },
  { date:"2025-02-22", stadium:"Stadio Arena Garibaldi", home:"Pisa SC", away:"SS Juve Stabia", homeScore:3, awayScore:1, attendance:null, competition:"Serie B" },
  { date:"2025-02-18", stadium:"Park Lane (Canvey Island)", home:"Canvey Island FC", away:"Chelmsford City", homeScore:0, awayScore:0, attendance:null, competition:"Essex Senior Cup Semi Final" },
  { date:"2025-02-15", stadium:"Raymond McEnhill Stadium", home:"Salisbury FC", away:"Chelmsford City", homeScore:1, awayScore:3, attendance:null, competition:"National League South" },
  { date:"2025-02-13", stadium:"Oakside Stadium", home:"Atlético London", away:"London Bees", homeScore:0, awayScore:2, attendance:null, competition:"Women's National League Division One South East" },
  { date:"2025-02-08", stadium:"Cherrywood Road", home:"Farnborough FC", away:"Chelmsford City", homeScore:3, awayScore:4, attendance:null, competition:"National League South" },
  { date:"2025-02-04", stadium:"Beveree Stadium", home:"Hampton and Richmond Borough", away:"Dorking Wanderers FC", homeScore:2, awayScore:2, attendance:null, competition:"National League South" },
  { date:"2025-02-01", stadium:"St. James' Park", home:"Newcastle United", away:"Fulham FC", homeScore:1, awayScore:2, attendance:null, competition:"Premier League" },
  { date:"2025-01-27", stadium:"Melbourne Stadium", home:"Chelmsford City", away:"Maidstone United FC", homeScore:0, awayScore:0, attendance:null, competition:"National League South" },
  { date:"2025-01-25", stadium:"BZA Gröpelingen Platz 4", home:"TuRa Bremen", away:"VfL 07 Bremen", homeScore:0, awayScore:0, attendance:null, competition:"Friendly" },
  { date:"2025-01-21", stadium:"The Meadow (Chesham)", home:"Chesham United FC", away:"Chelmsford City", homeScore:2, awayScore:2, attendance:null, competition:"National League South" },
  { date:"2025-01-18", stadium:"Grosvenor Vale", home:"Wealdstone FC", away:"Hartlepool United", homeScore:1, awayScore:1, attendance:null, competition:"National League" },
  { date:"2025-01-14", stadium:"Brisbane Road", home:"Leyton Orient", away:"Derby County", homeScore:1, awayScore:1, attendance:null, competition:"FA Cup" },
  { date:"2024-12-14", stadium:"St. James' Park", home:"Newcastle United", away:"Leicester City", homeScore:4, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2024-12-02", stadium:"Melbourne Stadium", home:"Chelmsford City", away:"Boreham Wood FC", homeScore:2, awayScore:3, attendance:null, competition:"National League South" },
  { date:"2024-11-30", stadium:"Molineux Stadium", home:"Wolverhampton Wanderers", away:"AFC Bournemouth", homeScore:2, awayScore:4, attendance:null, competition:"Premier League" },
  { date:"2024-11-26", stadium:"Brisbane Road", home:"Leyton Orient", away:"Huddersfield Town", homeScore:0, awayScore:2, attendance:null, competition:"League One" },
  { date:"2024-11-16", stadium:"New Lodge", home:"Billericay Town", away:"Bowers & Pitsea", homeScore:2, awayScore:1, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2024-11-09", stadium:"Broadfield Stadium", home:"Crawley Town", away:"Huddersfield Town", homeScore:2, awayScore:2, attendance:null, competition:"League One" },
  { date:"2024-11-02", stadium:"St. James' Park", home:"Newcastle United", away:"Arsenal FC", homeScore:1, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2024-10-30", stadium:"Villa Park", home:"Aston Villa", away:"Crystal Palace", homeScore:1, awayScore:2, attendance:null, competition:"EFL Cup" },
  { date:"2024-10-26", stadium:"Melbourne Stadium", home:"Chelmsford City", away:"Salisbury FC", homeScore:2, awayScore:1, attendance:null, competition:"National League South" },
  { date:"2024-10-21", stadium:"Vauxhall Road", home:"Hemel Hempstead Town FC", away:"Chelmsford City", homeScore:2, awayScore:2, attendance:null, competition:"National League South" },
  { date:"2024-10-19", stadium:"St. James' Park", home:"Newcastle United", away:"Brighton & Hove Albion", homeScore:0, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2024-10-15", stadium:"Champion Hill Stadium", home:"Dulwich Hamlet FC", away:"Binfield FC", homeScore:1, awayScore:4, attendance:null, competition:"Isthmian League Alan Turvey Trophy" },
  { date:"2024-10-12", stadium:"The Hive Stadium", home:"Barnet FC", away:"Chelmsford City", homeScore:4, awayScore:0, attendance:null, competition:"FA Cup Qualification" },
  { date:"2024-09-24", stadium:"Reynolds Field", home:"Hanwell Town", away:"Sholing FC", homeScore:0, awayScore:1, attendance:null, competition:"Southern League Premier Division South" },
  { date:"2024-09-14", stadium:"The Brentwood Centre Arena", home:"Brentwood Town FC", away:"Leiston FC", homeScore:2, awayScore:2, attendance:null, competition:"FA Cup Qualification" },
  { date:"2024-09-03", stadium:"Gallagher Stadium", home:"Maidstone United FC", away:"Chelmsford City", homeScore:1, awayScore:5, attendance:null, competition:"National League South" },
  { date:"2024-09-01", stadium:"St. James' Park", home:"Newcastle United", away:"Tottenham Hotspur", homeScore:2, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2024-08-27", stadium:"King Power Stadium", home:"Leicester City", away:"Tranmere Rovers", homeScore:4, awayScore:0, attendance:null, competition:"EFL Cup" },
  { date:"2024-08-26", stadium:"Melbourne Stadium", home:"Chelmsford City", away:"Chippenham Town FC", homeScore:1, awayScore:1, attendance:null, competition:"National League South" },
  { date:"2024-08-11", stadium:"Anfield", home:"Liverpool FC", away:"Sevilla FC", homeScore:4, awayScore:1, attendance:null, competition:"Friendly" },
  { date:"2024-08-10", stadium:"Goodison Park", home:"Everton FC", away:"AS Roma", homeScore:1, awayScore:1, attendance:null, competition:"Friendly" },
  { date:"2024-08-04", stadium:"Vitality Stadium", home:"AFC Bournemouth", away:"Rayo Vallecano", homeScore:1, awayScore:0, attendance:null, competition:"Friendly" },
  { date:"2024-07-30", stadium:"Simarco Stadium", home:"Witham Town FC", away:"Chelmsford City", homeScore:4, awayScore:3, attendance:null, competition:"Essex Tolleshunt D'Arcy Memorial Cup Final" },
  { date:"2024-07-27", stadium:"MKM Stadium", home:"Hull City", away:"Newcastle United", homeScore:0, awayScore:2, attendance:null, competition:"Friendly" },
  { date:"2024-07-24", stadium:"Melbourne Stadium", home:"Chelmsford City", away:"Milton Keynes Dons", homeScore:0, awayScore:1, attendance:null, competition:"Friendly" },
  { date:"2024-07-22", stadium:"Melbourne Stadium", home:"Chelmsford City", away:"Barnet FC", homeScore:1, awayScore:1, attendance:null, competition:"Friendly" },
  { date:"2024-07-13", stadium:"Gillette Stadium", home:"New England Revolution", away:"Orlando City", homeScore:1, awayScore:3, attendance:null, competition:"Major League Soccer" },
  { date:"2024-07-03", stadium:"Gillette Stadium", home:"New England Revolution", away:"Atlanta United FC", homeScore:2, awayScore:1, attendance:null, competition:"Major League Soccer" },
  { date:"2024-04-27", stadium:"Geodis Park", home:"Nashville SC", away:"San Jose Earthquakes", homeScore:1, awayScore:1, attendance:null, competition:"Major League Soccer" },
  { date:"2024-04-06", stadium:"Melbourne Stadium", home:"Chelmsford City", away:"Slough Town FC", homeScore:1, awayScore:1, attendance:null, competition:"National League South" },
  { date:"2024-03-29", stadium:"Cardiff City Stadium", home:"Cardiff City", away:"Sunderland AFC", homeScore:0, awayScore:2, attendance:null, competition:"Championship" },
  { date:"2024-03-23", stadium:"Kenilworth Road", home:"Hashtag United Women", away:"Newcastle United Women", homeScore:2, awayScore:1, attendance:null, competition:"Women's National League Cup Final" },
  { date:"2024-03-22", stadium:"London Stadium", home:"Spain", away:"Colombia", homeScore:0, awayScore:1, attendance:null, competition:"Friendly" },
  { date:"2024-03-16", stadium:"Meadowbank (Dorking)", home:"Dorking Wanderers FC", away:"Solihull Moors", homeScore:1, awayScore:1, attendance:null, competition:"National League" },
  { date:"2024-03-14", stadium:"London Stadium", home:"West Ham United", away:"SC Freiburg", homeScore:5, awayScore:0, attendance:null, competition:"UEFA Europa League Round of 16" },
  { date:"2024-03-12", stadium:"Brisbane Road", home:"Leyton Orient", away:"Port Vale", homeScore:0, awayScore:0, attendance:null, competition:"League One" },
  { date:"2024-03-03", stadium:"Turf Moor", home:"Burnley FC", away:"AFC Bournemouth", homeScore:0, awayScore:2, attendance:null, competition:"Premier League" },
  { date:"2024-03-02", stadium:"St. James' Park", home:"Newcastle United", away:"Wolverhampton Wanderers", homeScore:3, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2024-02-15", stadium:"Stamford Bridge", home:"Chelsea FC U21", away:"PSV Eindhoven U21", homeScore:1, awayScore:2, attendance:null, competition:"Premier League International Cup" },
  { date:"2024-02-10", stadium:"Adams Park", home:"Wycombe Wanderers", away:"Peterborough United", homeScore:5, awayScore:2, attendance:null, competition:"League One" },
  { date:"2024-02-03", stadium:"Old Chelmsfordians Sports Association", home:"Old Chelmsfordians", away:"Kelvedon Hatch", homeScore:1, awayScore:1, attendance:null, competition:"Essex Olympian League Premier Division" },
  { date:"2024-01-27", stadium:"Philips Stadion", home:"PSV Eindhoven", away:"Almere City FC", homeScore:2, awayScore:0, attendance:null, competition:"Eredivisie" },
  { date:"2024-01-22", stadium:"Melbourne Stadium", home:"Chelmsford City", away:"Welling United", homeScore:1, awayScore:0, attendance:null, competition:"National League South" },
  { date:"2024-01-20", stadium:"New Lodge", home:"Billericay Town", away:"Lewes FC", homeScore:5, awayScore:0, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2024-01-06", stadium:"Kuflink Stadium", home:"Ebbsfleet United", away:"Wealdstone FC", homeScore:2, awayScore:0, attendance:null, competition:"National League" },
  { date:"2024-01-05", stadium:"Gtech Community Stadium", home:"Brentford FC", away:"Wolverhampton Wanderers", homeScore:1, awayScore:1, attendance:null, competition:"FA Cup" },
  { date:"2024-01-01", stadium:"Melbourne Stadium", home:"Chelmsford City", away:"Braintree Town", homeScore:3, awayScore:0, attendance:null, competition:"National League South" },
  { date:"2023-12-30", stadium:"Park Drive (Maldon)", home:"Maldon and Tiptree FC", away:"Walthamstow FC", homeScore:4, awayScore:0, attendance:null, competition:"Isthmian League North Division" },
  { date:"2023-12-26", stadium:"St. James' Park", home:"Newcastle United", away:"Nottingham Forest", homeScore:1, awayScore:3, attendance:null, competition:"Premier League" },
  { date:"2023-12-23", stadium:"Fantastic Media Welfare Ground", home:"Emley AFC", away:"Bottesford Town", homeScore:9, awayScore:2, attendance:null, competition:"Northern Counties East Premier Division" },
  { date:"2023-12-19", stadium:"Yorkshire Payments Stadium", home:"Brighouse Town", away:"Campion AFC", homeScore:0, awayScore:1, attendance:null, competition:"West Riding County Cup" },
  { date:"2023-12-16", stadium:"St. James' Park", home:"Newcastle United", away:"Fulham FC", homeScore:3, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2023-12-13", stadium:"St. James' Park", home:"Newcastle United", away:"AC Milan", homeScore:1, awayScore:2, attendance:null, competition:"UEFA Champions League Group Stage" },
  { date:"2023-11-25", stadium:"Melbourne Stadium", home:"Chelmsford City", away:"Truro City", homeScore:1, awayScore:2, attendance:null, competition:"National League South" },
  { date:"2023-11-20", stadium:"Melbourne Stadium", home:"Chelmsford City", away:"Maidstone United FC", homeScore:0, awayScore:1, attendance:null, competition:"National League South" },
  { date:"2023-11-18", stadium:"Stamford Bridge", home:"Chelsea FC Women", away:"Liverpool FC Women", homeScore:5, awayScore:1, attendance:null, competition:"Women's Super League" },
  { date:"2023-11-11", stadium:"Melbourne Stadium", home:"Chelmsford City", away:"Chippenham Town FC", homeScore:2, awayScore:2, attendance:null, competition:"National League South" },
  { date:"2023-11-04", stadium:"The Den", home:"Millwall FC", away:"Southampton FC", homeScore:0, awayScore:1, attendance:null, competition:"Championship" },
  { date:"2023-11-01", stadium:"Portman Road", home:"Ipswich Town", away:"Fulham FC", homeScore:1, awayScore:3, attendance:null, competition:"EFL Cup" },
  { date:"2023-10-25", stadium:"Gateshead International Stadium", home:"Newcastle United U19", away:"Borussia Dortmund U19", homeScore:1, awayScore:2, attendance:null, competition:"UEFA Youth League" },
  { date:"2023-10-25", stadium:"St. James' Park", home:"Newcastle United", away:"Borussia Dortmund", homeScore:0, awayScore:1, attendance:null, competition:"UEFA Champions League Group Stage" },
  { date:"2023-10-13", stadium:"Wembley Stadium", home:"England", away:"Australia", homeScore:1, awayScore:0, attendance:null, competition:"Friendly" },
  { date:"2023-10-04", stadium:"Gateshead International Stadium", home:"Newcastle United U19", away:"Paris Saint-Germain U19", homeScore:0, awayScore:1, attendance:null, competition:"UEFA Youth League" },
  { date:"2023-10-04", stadium:"St. James' Park", home:"Newcastle United", away:"Paris Saint-Germain", homeScore:4, awayScore:1, attendance:null, competition:"UEFA Champions League Group Stage" },
  { date:"2023-10-02", stadium:"Melbourne Stadium", home:"Chelmsford City", away:"Bromsgrove Sporting FC", homeScore:3, awayScore:0, attendance:null, competition:"FA Cup Qualification" },
  { date:"2023-09-26", stadium:"Portman Road", home:"Ipswich Town", away:"Wolverhampton Wanderers", homeScore:3, awayScore:2, attendance:null, competition:"EFL Cup" },
  { date:"2023-09-16", stadium:"St. James' Park", home:"Newcastle United", away:"Brentford FC", homeScore:1, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2023-09-09", stadium:"Len Salmon Stadium", home:"Hashtag United", away:"Kingstonian FC", homeScore:2, awayScore:2, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2023-09-04", stadium:"Melbourne Stadium", home:"Chelmsford City", away:"Hemel Hempstead Town FC", homeScore:1, awayScore:2, attendance:null, competition:"National League South" },
  { date:"2023-09-02", stadium:"American Express Stadium", home:"Brighton & Hove Albion", away:"Newcastle United", homeScore:3, awayScore:1, attendance:null, competition:"" },
  { date:"2023-08-30", stadium:"City Ground", home:"Nottingham Forest", away:"Burnley FC", homeScore:0, awayScore:1, attendance:null, competition:"EFL Cup" },
  { date:"2023-08-28", stadium:"Meadow Lane (Nottingham)", home:"Nottingham Forest U21", away:"Arsenal FC U21", homeScore:2, awayScore:0, attendance:null, competition:"Premier League 2" },
  { date:"2023-08-15", stadium:"Cressing Road", home:"Braintree Town", away:"Maidstone United FC", homeScore:1, awayScore:2, attendance:null, competition:"National League South" },
  { date:"2023-08-12", stadium:"St. James' Park", home:"Newcastle United", away:"Aston Villa", homeScore:5, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2023-08-09", stadium:"Portman Road", home:"Ipswich Town", away:"Bristol Rovers", homeScore:2, awayScore:0, attendance:null, competition:"EFL Cup" },
  { date:"2023-08-05", stadium:"Craven Cottage", home:"Fulham FC", away:"TSG 1899 Hoffenheim", homeScore:2, awayScore:1, attendance:null, competition:"Friendly" },
  { date:"2023-07-29", stadium:"WWK ARENA", home:"FC Augsburg", away:"AFC Ajax", homeScore:3, awayScore:1, attendance:null, competition:"Friendly" },
  { date:"2023-07-28", stadium:"Grünwalder Stadion", home:"FC Bayern München II", away:"Türkgücü München", homeScore:1, awayScore:4, attendance:null, competition:"Regionalliga Bayern" },
  { date:"2023-07-22", stadium:"Colchester Community Stadium", home:"Colchester United", away:"Peterborough United", homeScore:0, awayScore:1, attendance:null, competition:"Friendly" },
  { date:"2023-05-14", stadium:"Wembley Stadium", home:"Manchester United Women", away:"Chelsea FC Women", homeScore:0, awayScore:1, attendance:null, competition:"Women's FA Cup Final" },
  { date:"2023-05-02", stadium:"Melbourne Stadium", home:"Chelmsford City", away:"St Albans City", homeScore:0, awayScore:1, attendance:null, competition:"National League South Play-off Eliminator A" },
  { date:"2023-04-29", stadium:"Melbourne Stadium", home:"Chelmsford City", away:"Taunton Town FC", homeScore:1, awayScore:2, attendance:null, competition:"National League South" },
  { date:"2023-04-02", stadium:"St. James' Park", home:"Newcastle United", away:"Manchester United", homeScore:2, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2023-03-12", stadium:"St. James' Park", home:"Newcastle United", away:"Wolverhampton Wanderers", homeScore:2, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2023-03-04", stadium:"John Smith's Stadium", home:"Huddersfield Town", away:"Coventry City", homeScore:0, awayScore:4, attendance:null, competition:"Championship" },
  { date:"2023-02-26", stadium:"Wembley Stadium", home:"Manchester United", away:"Newcastle United", homeScore:2, awayScore:0, attendance:null, competition:"EFL Cup Final" },
  { date:"2023-02-19", stadium:"Volksparkstadion", home:"Hamburger SV", away:"Arminia Bielefeld", homeScore:2, awayScore:1, attendance:null, competition:"2. Bundesliga" },
  { date:"2023-02-04", stadium:"St. James' Park", home:"Newcastle United", away:"West Ham United", homeScore:1, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2023-01-31", stadium:"St. James' Park", home:"Newcastle United", away:"Southampton FC", homeScore:2, awayScore:1, attendance:null, competition:"EFL Cup" },
  { date:"2022-11-26", stadium:"Horsfall Stadium", home:"Bradford Park Avenue AFC", away:"Boston United", homeScore:2, awayScore:1, attendance:null, competition:"National League North" },
  { date:"2022-11-12", stadium:"St. James' Park", home:"Newcastle United", away:"Chelsea FC", homeScore:1, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2022-11-08", stadium:"The Cherry Red Records Stadium", home:"AFC Wimbledon", away:"Leyton Orient", homeScore:2, awayScore:0, attendance:null, competition:"League Two" },
  { date:"2022-11-02", stadium:"John Smith's Stadium", home:"Huddersfield Town", away:"Sunderland AFC", homeScore:0, awayScore:2, attendance:null, competition:"Championship" },
  { date:"2022-10-29", stadium:"St. James' Park", home:"Newcastle United", away:"Aston Villa", homeScore:4, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2022-10-08", stadium:"St. James' Park", home:"Newcastle United", away:"Brentford FC", homeScore:5, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2022-09-26", stadium:"Wembley Stadium", home:"England", away:"Germany", homeScore:3, awayScore:3, attendance:null, competition:"UEFA Nations League A Group Stage" },
  { date:"2022-08-09", stadium:"The Valley", home:"Charlton Athletic", away:"Queens Park Rangers", homeScore:1, awayScore:1, attendance:null, competition:"EFL Cup" },
  { date:"2022-05-02", stadium:"New Lodge", home:"Billericay Town", away:"Ebbsfleet United", homeScore:1, awayScore:2, attendance:null, competition:"National League South" },
  { date:"2022-04-30", stadium:"St. James' Park", home:"Newcastle United", away:"Liverpool FC", homeScore:0, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2022-04-16", stadium:"Coles Park Stadium", home:"Haringey Borough", away:"Cheshunt FC", homeScore:2, awayScore:4, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2022-04-15", stadium:"Mayesbrook Park", home:"Romford FC", away:"Aveley FC", homeScore:1, awayScore:4, attendance:null, competition:"Isthmian League North Division" },
  { date:"2022-04-15", stadium:"Hornchurch Stadium", home:"Hornchurch FC", away:"Brightlingsea Regent", homeScore:3, awayScore:0, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2022-03-19", stadium:"John Smith's Stadium", home:"Huddersfield Town", away:"AFC Bournemouth", homeScore:0, awayScore:3, attendance:null, competition:"Championship" },
  { date:"2022-03-05", stadium:"St. James' Park", home:"Newcastle United", away:"Brighton & Hove Albion", homeScore:2, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2022-02-23", stadium:"John Smith's Stadium", home:"Huddersfield Town", away:"Cardiff City", homeScore:2, awayScore:1, attendance:null, competition:"Championship" },
  { date:"2022-02-05", stadium:"John Smith's Stadium", home:"Huddersfield Town", away:"Barnsley FC", homeScore:1, awayScore:0, attendance:null, competition:"FA Cup" },
  { date:"2022-01-29", stadium:"Rookery Hill", home:"East Thurrock United FC", away:"Haringey Borough", homeScore:1, awayScore:3, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2021-10-30", stadium:"St. James' Park", home:"Newcastle United", away:"Chelsea FC", homeScore:0, awayScore:3, attendance:null, competition:"Premier League" },
  { date:"2021-10-16", stadium:"Edgeley Park", home:"Stockport County", away:"Stamford AFC", homeScore:3, awayScore:0, attendance:null, competition:"FA Cup Qualification" },
  { date:"2021-10-02", stadium:"Alder Street", home:"Atherton Collieries AFC", away:"Marine FC", homeScore:0, awayScore:0, attendance:null, competition:"FA Cup Qualification" },
  { date:"2021-09-28", stadium:"Coles Park Stadium", home:"Haringey Borough", away:"Potters Bar Town FC", homeScore:2, awayScore:2, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2021-09-18", stadium:"York Community Stadium", home:"York City", away:"Hebburn Town", homeScore:3, awayScore:0, attendance:null, competition:"FA Cup Qualification" },
  { date:"2021-09-10", stadium:"Fantastic Media Welfare Ground", home:"Emley AFC", away:"SJR Worksop", homeScore:5, awayScore:2, attendance:null, competition:"" },
  { date:"2021-09-06", stadium:"Clarence Park (St Albans)", home:"Watford FC U23", away:"Newcastle United U23", homeScore:2, awayScore:0, attendance:null, competition:"Premier League Cup Group Stage" },
  { date:"2021-09-05", stadium:"Park View Road", home:"Erith & Belvedere FC", away:"Chertsey Town FC", homeScore:0, awayScore:4, attendance:null, competition:"FA Cup Qualification" },
  { date:"2021-09-04", stadium:"Peterborough Sports & Leisure Club", home:"Peterborough Sports", away:"Haringey Borough", homeScore:2, awayScore:1, attendance:null, competition:"FA Cup Qualification" },
  { date:"2021-05-25", stadium:"Coles Park Stadium", home:"Haringey Borough", away:"Hanwell Town", homeScore:2, awayScore:2, attendance:null, competition:"London Senior Cup" },
  { date:"2021-05-22", stadium:"Wadham Lodge", home:"Clapton CFC", away:"Sporting Hackney", homeScore:1, awayScore:1, attendance:null, competition:"" },
  { date:"2021-05-17", stadium:"Selhurst Park", home:"Crystal Palace U23", away:"Wolverhampton Wanderers U23", homeScore:3, awayScore:2, attendance:null, competition:"U23 Premier League Division 2" },
  { date:"2020-10-13", stadium:"Coles Park Stadium", home:"Haringey Borough", away:"Bracknell Town", homeScore:5, awayScore:1, attendance:null, competition:"FA Cup Qualification" },
  { date:"2020-10-05", stadium:"Coles Park Stadium", home:"Haringey Borough", away:"East Thurrock United FC", homeScore:3, awayScore:1, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2020-09-28", stadium:"Coles Park Stadium", home:"Haringey Borough", away:"Leatherhead FC", homeScore:0, awayScore:1, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2020-03-07", stadium:"St Mary's Stadium", home:"Southampton FC", away:"Newcastle United", homeScore:0, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2020-01-29", stadium:"Meadow Park (Borehamwood)", home:"Arsenal Women FC", away:"Manchester City Women", homeScore:2, awayScore:1, attendance:null, competition:"WSL Cup Semi Final" },
  { date:"2020-01-27", stadium:"Coles Park Stadium", home:"Haringey Borough", away:"Carshalton Athletic FC", homeScore:2, awayScore:2, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2020-01-07", stadium:"Maurice Rebak Stadium", home:"Wingate & Finchley FC", away:"Leatherhead FC", homeScore:1, awayScore:2, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2020-01-04", stadium:"Coles Park Stadium", home:"Haringey Borough", away:"Lewes FC", homeScore:0, awayScore:1, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2019-12-26", stadium:"Fantastic Media Welfare Ground", home:"Emley AFC", away:"Shelley FC", homeScore:1, awayScore:3, attendance:null, competition:"North West Counties League Div One North" },
  { date:"2019-12-09", stadium:"London Stadium", home:"West Ham United", away:"Arsenal FC", homeScore:1, awayScore:3, attendance:null, competition:"Premier League" },
  { date:"2019-12-07", stadium:"St Paul's Sports Ground", home:"Fisher FC", away:"Erith & Belvedere FC", homeScore:1, awayScore:1, attendance:null, competition:"Southern Counties East League Premier Division" },
  { date:"2019-12-03", stadium:"Lantern Stadium", home:"Potters Bar Town FC", away:"Brightlingsea Regent", homeScore:4, awayScore:2, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2019-11-30", stadium:"St. James' Park", home:"Newcastle United", away:"Manchester City", homeScore:2, awayScore:2, attendance:null, competition:"Premier League" },
  { date:"2019-11-18", stadium:"Coles Park Stadium", home:"Haringey Borough", away:"Hornchurch FC", homeScore:1, awayScore:1, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2019-11-17", stadium:"Tottenham Hotspur Stadium", home:"Tottenham Hotspur Women", away:"Arsenal Women FC", homeScore:0, awayScore:2, attendance:null, competition:"Women's Super League" },
  { date:"2019-11-16", stadium:"Coles Park Stadium", home:"Haringey Borough", away:"Bishop's Stortford FC", homeScore:2, awayScore:1, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2019-11-02", stadium:"London Stadium", home:"West Ham United", away:"Newcastle United", homeScore:2, awayScore:3, attendance:null, competition:"Premier League" },
  { date:"2019-10-29", stadium:"Coles Park Stadium", home:"Haringey Borough", away:"Yeovil Town", homeScore:0, awayScore:3, attendance:null, competition:"FA Cup Qualification" },
  { date:"2019-10-26", stadium:"Coles Park Stadium", home:"Haringey Borough", away:"Horsham FC", homeScore:3, awayScore:0, attendance:null, competition:"FA Trophy Qualification" },
  { date:"2019-10-22", stadium:"Queen Elizabeth II Stadium", home:"Enfield Town FC", away:"Hornchurch FC", homeScore:1, awayScore:1, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2019-10-15", stadium:"Victoria Road (Dagenham)", home:"AS Monaco U21", away:"Jong Feyenoord", homeScore:3, awayScore:1, attendance:null, competition:"" },
  { date:"2019-10-02", stadium:"The Valley", home:"Charlton Athletic", away:"Swansea City", homeScore:1, awayScore:2, attendance:null, competition:"Championship" },
  { date:"2019-09-30", stadium:"Coles Park Stadium", home:"Haringey Borough", away:"Kingstonian FC", homeScore:0, awayScore:1, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2019-09-29", stadium:"London Stadium", home:"West Ham United Women", away:"Tottenham Hotspur Women", homeScore:0, awayScore:2, attendance:null, competition:"Women's Super League" },
  { date:"2019-09-28", stadium:"Hayes Lane", home:"Cray Wanderers FC", away:"East Thurrock United FC", homeScore:1, awayScore:1, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2019-09-26", stadium:"Meadow Park (Borehamwood)", home:"Arsenal Women FC", away:"ACF Fiorentina Femminile", homeScore:2, awayScore:0, attendance:null, competition:"UEFA Women's Champions League Round of 32" },
  { date:"2019-09-24", stadium:"Emirates Stadium", home:"Arsenal FC", away:"Nottingham Forest", homeScore:5, awayScore:0, attendance:null, competition:"EFL Cup" },
  { date:"2019-09-14", stadium:"Hayes Lane", home:"Cray Wanderers FC", away:"Haringey Borough", homeScore:1, awayScore:1, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2019-08-19", stadium:"EBB Stadium", home:"Chelsea FC U23", away:"Liverpool FC U23", homeScore:3, awayScore:0, attendance:null, competition:"U23 Premier League Division 1" },
  { date:"2019-08-17", stadium:"Carrow Road", home:"Norwich City", away:"Newcastle United", homeScore:3, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2019-08-16", stadium:"Enfield Training Centre", home:"Tottenham Hotspur U23", away:"Manchester City U23", homeScore:3, awayScore:1, attendance:null, competition:"U23 Premier League Division 1" },
  { date:"2019-08-11", stadium:"St. James' Park", home:"Newcastle United", away:"Arsenal FC", homeScore:0, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2019-07-20", stadium:"New Bucks Head", home:"AFC Telford United", away:"Coventry City", homeScore:1, awayScore:1, attendance:null, competition:"" },
  { date:"2019-07-11", stadium:"Coles Park Stadium", home:"Haringey Borough", away:"Aldershot Town", homeScore:0, awayScore:4, attendance:null, competition:"Friendly" },
  { date:"2019-05-26", stadium:"Wembley Stadium", home:"Charlton Athletic", away:"Sunderland AFC", homeScore:2, awayScore:1, attendance:null, competition:"League One Playoff" },
  { date:"2019-05-17", stadium:"The Valley", home:"Charlton Athletic", away:"Doncaster Rovers", homeScore:2, awayScore:3, attendance:null, competition:"League One Playoff" },
  { date:"2019-05-02", stadium:"Coles Park Stadium", home:"Haringey Borough", away:"Tonbridge Angels", homeScore:1, awayScore:2, attendance:null, competition:"Isthmian League Premier Division Play-Off Semi Final" },
  { date:"2019-04-20", stadium:"St. James' Park", home:"Newcastle United", away:"Southampton FC", homeScore:3, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2019-04-13", stadium:"Coles Park Stadium", home:"Haringey Borough", away:"Kingstonian FC", homeScore:2, awayScore:0, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2019-04-09", stadium:"Brisbane Road", home:"Leyton Orient", away:"Eastleigh FC", homeScore:3, awayScore:2, attendance:null, competition:"National League" },
  { date:"2019-03-23", stadium:"Coles Park Stadium", home:"Haringey Borough", away:"Enfield Town FC", homeScore:3, awayScore:1, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2019-03-16", stadium:"Brisbane Road", home:"Leyton Orient", away:"AFC Telford United", homeScore:1, awayScore:0, attendance:null, competition:"FA Trophy" },
  { date:"2019-03-13", stadium:"Rush Green Stadium", home:"West Ham United Women", away:"Everton FC Women", homeScore:0, awayScore:1, attendance:null, competition:"Women's Super League" },
  { date:"2019-03-10", stadium:"Emirates Stadium", home:"Arsenal FC", away:"Manchester United", homeScore:2, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2019-03-09", stadium:"Kingsmeadow Stadium", home:"AFC Wimbledon", away:"Doncaster Rovers", homeScore:2, awayScore:0, attendance:null, competition:"League One" },
  { date:"2019-03-02", stadium:"London Stadium", home:"West Ham United", away:"Newcastle United", homeScore:2, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2019-02-21", stadium:"Emirates Stadium", home:"Arsenal FC", away:"FC BATE Borisov", homeScore:3, awayScore:0, attendance:null, competition:"UEFA Europa League Round of 32" },
  { date:"2019-02-16", stadium:"Coles Park Stadium", home:"Haringey Borough", away:"Leatherhead FC", homeScore:0, awayScore:3, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2019-01-27", stadium:"The SMISA Stadium", home:"St. Mirren FC", away:"Hibernian FC", homeScore:1, awayScore:3, attendance:null, competition:"Scottish Premiership" },
  { date:"2019-01-26", stadium:"Celtic Park", home:"Celtic FC", away:"Hamilton Academical", homeScore:3, awayScore:0, attendance:null, competition:"Scottish Premiership" },
  { date:"2019-01-19", stadium:"Estadio La Rosaleda", home:"Málaga CF", away:"CD Lugo", homeScore:2, awayScore:1, attendance:null, competition:"Segunda División" },
  { date:"2019-01-05", stadium:"Sandygate Road", home:"Hallam FC", away:"Emley AFC", homeScore:3, awayScore:1, attendance:null, competition:"Northern Counties East Division One" },
  { date:"2018-12-29", stadium:"Coles Park Stadium", home:"Haringey Borough", away:"Merstham FC", homeScore:2, awayScore:2, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2018-12-22", stadium:"London Stadium", home:"West Ham United", away:"Watford FC", homeScore:0, awayScore:2, attendance:null, competition:"Premier League" },
  { date:"2018-12-17", stadium:"Coles Park Stadium", home:"Haringey Borough", away:"Carshalton Athletic FC", homeScore:3, awayScore:1, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2018-12-10", stadium:"Coles Park Stadium", home:"Haringey Borough", away:"Bishop's Stortford FC", homeScore:3, awayScore:1, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2018-12-01", stadium:"St. James' Park", home:"Newcastle United", away:"West Ham United", homeScore:0, awayScore:3, attendance:null, competition:"Premier League" },
  { date:"2018-11-24", stadium:"Coles Park Stadium", home:"Haringey Borough", away:"Hornchurch FC", homeScore:3, awayScore:1, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2018-11-19", stadium:"Coles Park Stadium", home:"Haringey Borough", away:"Dorking Wanderers FC", homeScore:3, awayScore:2, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2018-11-12", stadium:"Coles Park Stadium", home:"Haringey Borough", away:"Tonbridge Angels", homeScore:4, awayScore:0, attendance:null, competition:"Isthmian League Premier Division" },
  { date:"2018-11-10", stadium:"St. James' Park", home:"Newcastle United", away:"AFC Bournemouth", homeScore:2, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2018-09-08", stadium:"The Hive Stadium", home:"Barnet FC", away:"Maidenhead United", homeScore:1, awayScore:0, attendance:null, competition:"National League" },
  { date:"2018-08-07", stadium:"Brisbane Road", home:"Leyton Orient", away:"Ebbsfleet United", homeScore:1, awayScore:1, attendance:null, competition:"National League" },
  { date:"2018-07-28", stadium:"Loftus Road", home:"Queens Park Rangers", away:"1. FC Union Berlin", homeScore:3, awayScore:0, attendance:null, competition:"Friendly" },
  { date:"2018-06-30", stadium:"Gillette Stadium", home:"New England Revolution", away:"D.C. United", homeScore:3, awayScore:2, attendance:null, competition:"Major League Soccer" },
  { date:"2018-05-28", stadium:"Wembley Stadium", home:"Exeter City", away:"Coventry City", homeScore:1, awayScore:3, attendance:null, competition:"League Two Playoff Final" },
  { date:"2018-05-27", stadium:"Wembley Stadium", home:"Shrewsbury Town", away:"Rotherham United", homeScore:1, awayScore:2, attendance:null, competition:"League One Playoff Final" },
  { date:"2018-05-13", stadium:"London Stadium", home:"West Ham United", away:"Everton FC", homeScore:3, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2018-04-24", stadium:"Meadow Park (Borehamwood)", home:"Arsenal Women FC", away:"Liverpool FC Women", homeScore:3, awayScore:0, attendance:null, competition:"Women's Super League" },
  { date:"2018-04-08", stadium:"Wembley Stadium", home:"Lincoln City", away:"Shrewsbury Town", homeScore:1, awayScore:0, attendance:null, competition:"EFL Trophy Final" },
  { date:"2018-02-07", stadium:"Wembley Stadium", home:"Tottenham Hotspur", away:"Newport County AFC", homeScore:2, awayScore:0, attendance:null, competition:"FA Cup" },
  { date:"2018-02-03", stadium:"Select Car Leasing Stadium", home:"Reading FC", away:"Millwall FC", homeScore:0, awayScore:2, attendance:null, competition:"Championship" },
  { date:"2018-01-16", stadium:"London Stadium", home:"West Ham United", away:"Shrewsbury Town", homeScore:1, awayScore:0, attendance:null, competition:"FA Cup" },
  { date:"2017-12-30", stadium:"Brunton Park", home:"Carlisle United", away:"Coventry City", homeScore:0, awayScore:1, attendance:null, competition:"League Two" },
  { date:"2017-12-27", stadium:"St. James' Park", home:"Newcastle United", away:"Manchester City", homeScore:0, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2017-12-07", stadium:"Emirates Stadium", home:"Arsenal FC", away:"FC BATE Borisov", homeScore:6, awayScore:0, attendance:null, competition:"UEFA Europa League Group Stage" },
  { date:"2017-11-25", stadium:"St. James' Park", home:"Newcastle United", away:"Watford FC", homeScore:0, awayScore:3, attendance:null, competition:"Premier League" },
  { date:"2017-10-24", stadium:"Emirates Stadium", home:"Arsenal FC", away:"Norwich City", homeScore:2, awayScore:1, attendance:null, competition:"EFL Cup" },
  { date:"2017-09-30", stadium:"Adams Park", home:"Wycombe Wanderers", away:"Barnet FC", homeScore:3, awayScore:1, attendance:null, competition:"League Two" },
  { date:"2017-09-24", stadium:"American Express Stadium", home:"Brighton & Hove Albion", away:"Newcastle United", homeScore:1, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2017-08-12", stadium:"Brisbane Road", home:"Leyton Orient", away:"Maidstone United FC", homeScore:2, awayScore:0, attendance:null, competition:"National League" },
  { date:"2017-08-06", stadium:"St. James' Park", home:"Newcastle United", away:"Hellas Verona FC", homeScore:2, awayScore:0, attendance:null, competition:"Friendly" },
  { date:"2017-07-30", stadium:"Emirates Stadium", home:"Arsenal FC", away:"Sevilla FC", homeScore:1, awayScore:2, attendance:null, competition:"Emirates Cup" },
  { date:"2017-07-22", stadium:"Griffin Park (Demolished)", home:"Brentford FC", away:"Southampton FC", homeScore:2, awayScore:2, attendance:null, competition:"Friendly" },
  { date:"2017-05-28", stadium:"Wembley Stadium", home:"Blackpool FC", away:"Exeter City", homeScore:2, awayScore:1, attendance:null, competition:"League Two Playoff Final" },
  { date:"2017-04-22", stadium:"Old Spotted Dog Ground", home:"Clapton FC", away:"Burnham Ramblers FC", homeScore:7, awayScore:0, attendance:null, competition:"Essex Senior Football League" },
  { date:"2017-04-15", stadium:"Old Spotted Dog Ground", home:"Clapton FC", away:"Ilford FC", homeScore:2, awayScore:0, attendance:null, competition:"Essex Senior Football League" },
  { date:"2017-03-18", stadium:"Roots Hall", home:"Southend United", away:"Walsall FC", homeScore:3, awayScore:2, attendance:null, competition:"League One" },
  { date:"2017-03-11", stadium:"The Valley", home:"Charlton Athletic", away:"Walsall FC", homeScore:1, awayScore:1, attendance:null, competition:"League One" },
  { date:"2017-03-04", stadium:"Old Spotted Dog Ground", home:"Clapton FC", away:"Hullbridge Sports", homeScore:4, awayScore:1, attendance:null, competition:"Essex Senior Football League" },
  { date:"2017-02-20", stadium:"St. James' Park", home:"Newcastle United", away:"Aston Villa", homeScore:2, awayScore:0, attendance:null, competition:"Championship" },
  { date:"2017-02-14", stadium:"Brunton Park", home:"Carlisle United", away:"Doncaster Rovers", homeScore:2, awayScore:1, attendance:null, competition:"League Two" },
  { date:"2017-02-04", stadium:"St Andrew's Stadium", home:"Birmingham City", away:"Fulham FC", homeScore:1, awayScore:0, attendance:null, competition:"Championship" },
  { date:"2016-12-30", stadium:"St. James' Park", home:"Newcastle United", away:"Nottingham Forest", homeScore:3, awayScore:1, attendance:null, competition:"Championship" },
  { date:"2016-12-26", stadium:"St. James' Park", home:"Newcastle United", away:"Sheffield Wednesday", homeScore:0, awayScore:1, attendance:null, competition:"Championship" },
  { date:"2016-12-14", stadium:"The Brick Community Stadium", home:"Wigan Athletic", away:"Newcastle United", homeScore:0, awayScore:2, attendance:null, competition:"Championship" },
  { date:"2016-12-10", stadium:"St. James' Park", home:"Newcastle United", away:"Birmingham City", homeScore:4, awayScore:0, attendance:null, competition:"Championship" },
  { date:"2016-11-26", stadium:"St. James' Park", home:"Newcastle United", away:"Blackburn Rovers", homeScore:0, awayScore:1, attendance:null, competition:"Championship" },
  { date:"2016-11-05", stadium:"St. James' Park", home:"Newcastle United", away:"Cardiff City", homeScore:2, awayScore:1, attendance:null, competition:"Championship" },
  { date:"2016-10-22", stadium:"St. James' Park", home:"Newcastle United", away:"Ipswich Town", homeScore:3, awayScore:0, attendance:null, competition:"Championship" },
  { date:"2016-10-15", stadium:"St. James' Park", home:"Newcastle United", away:"Brentford FC", homeScore:3, awayScore:1, attendance:null, competition:"Championship" },
  { date:"2016-09-28", stadium:"St. James' Park", home:"Newcastle United", away:"Norwich City", homeScore:4, awayScore:3, attendance:null, competition:"Championship" },
  { date:"2016-09-17", stadium:"St. James' Park", home:"Newcastle United", away:"Wolverhampton Wanderers", homeScore:0, awayScore:2, attendance:null, competition:"Championship" },
  { date:"2016-08-27", stadium:"St. James' Park", home:"Newcastle United", away:"Brighton & Hove Albion", homeScore:2, awayScore:0, attendance:null, competition:"Championship" },
  { date:"2016-08-17", stadium:"St. James' Park", home:"Newcastle United", away:"Reading FC", homeScore:4, awayScore:1, attendance:null, competition:"Championship" },
  { date:"2016-08-13", stadium:"St. James' Park", home:"Newcastle United", away:"Huddersfield Town", homeScore:1, awayScore:2, attendance:null, competition:"Championship" },
  { date:"2016-08-06", stadium:"Galabank", home:"Annan Athletic", away:"Stirling Albion", homeScore:3, awayScore:2, attendance:null, competition:"Scottish League Two" },
  { date:"2016-05-15", stadium:"St. James' Park", home:"Newcastle United", away:"Tottenham Hotspur", homeScore:5, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2016-04-30", stadium:"St. James' Park", home:"Newcastle United", away:"Crystal Palace", homeScore:1, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2016-04-19", stadium:"St. James' Park", home:"Newcastle United", away:"Manchester City", homeScore:1, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2016-04-16", stadium:"St. James' Park", home:"Newcastle United", away:"Swansea City", homeScore:3, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2016-03-20", stadium:"St. James' Park", home:"Newcastle United", away:"Sunderland AFC", homeScore:1, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2016-03-05", stadium:"St. James' Park", home:"Newcastle United", away:"AFC Bournemouth", homeScore:1, awayScore:3, attendance:null, competition:"Premier League" },
  { date:"2016-02-06", stadium:"St. James' Park", home:"Newcastle United", away:"West Bromwich Albion", homeScore:1, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2016-01-16", stadium:"St. James' Park", home:"Newcastle United", away:"West Ham United", homeScore:2, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2016-01-12", stadium:"St. James' Park", home:"Newcastle United", away:"Manchester United", homeScore:3, awayScore:3, attendance:null, competition:"Premier League" },
  { date:"2015-12-26", stadium:"St. James' Park", home:"Newcastle United", away:"Everton FC", homeScore:0, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2015-12-19", stadium:"St. James' Park", home:"Newcastle United", away:"Aston Villa", homeScore:1, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2015-12-06", stadium:"St. James' Park", home:"Newcastle United", away:"Liverpool FC", homeScore:2, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2015-11-21", stadium:"St. James' Park", home:"Newcastle United", away:"Leicester City", homeScore:0, awayScore:3, attendance:null, competition:"Premier League" },
  { date:"2015-10-31", stadium:"St. James' Park", home:"Newcastle United", away:"Stoke City", homeScore:0, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2015-10-18", stadium:"St. James' Park", home:"Newcastle United", away:"Norwich City", homeScore:6, awayScore:2, attendance:null, competition:"Premier League" },
  { date:"2015-09-26", stadium:"St. James' Park", home:"Newcastle United", away:"Chelsea FC", homeScore:2, awayScore:2, attendance:null, competition:"Premier League" },
  { date:"2015-09-19", stadium:"St. James' Park", home:"Newcastle United", away:"Watford FC", homeScore:1, awayScore:2, attendance:null, competition:"Premier League" },
  { date:"2015-08-29", stadium:"St. James' Park", home:"Newcastle United", away:"Arsenal FC", homeScore:0, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2015-08-09", stadium:"St. James' Park", home:"Newcastle United", away:"Southampton FC", homeScore:2, awayScore:2, attendance:null, competition:"Premier League" },
  { date:"2015-07-26", stadium:"Emirates Stadium", home:"Arsenal FC", away:"VfL Wolfsburg", homeScore:1, awayScore:0, attendance:null, competition:"Emirates Cup" },
  { date:"2015-05-24", stadium:"St. James' Park", home:"Newcastle United", away:"West Ham United", homeScore:2, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2015-05-09", stadium:"St. James' Park", home:"Newcastle United", away:"West Bromwich Albion", homeScore:1, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2015-04-25", stadium:"St. James' Park", home:"Newcastle United", away:"Swansea City", homeScore:2, awayScore:3, attendance:null, competition:"Premier League" },
  { date:"2015-04-19", stadium:"St. James' Park", home:"Newcastle United", away:"Tottenham Hotspur", homeScore:1, awayScore:3, attendance:null, competition:"Premier League" },
  { date:"2015-03-21", stadium:"St. James' Park", home:"Newcastle United", away:"Arsenal FC", homeScore:1, awayScore:2, attendance:null, competition:"Premier League" },
  { date:"2015-03-04", stadium:"St. James' Park", home:"Newcastle United", away:"Manchester United", homeScore:0, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2015-02-28", stadium:"St. James' Park", home:"Newcastle United", away:"Aston Villa", homeScore:1, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2015-02-08", stadium:"St. James' Park", home:"Newcastle United", away:"Stoke City", homeScore:1, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2015-01-17", stadium:"St. James' Park", home:"Newcastle United", away:"Southampton FC", homeScore:1, awayScore:2, attendance:null, competition:"Premier League" },
  { date:"2015-01-01", stadium:"St. James' Park", home:"Newcastle United", away:"Burnley FC", homeScore:3, awayScore:3, attendance:null, competition:"Premier League" },
  { date:"2014-12-28", stadium:"St. James' Park", home:"Newcastle United", away:"Everton FC", homeScore:3, awayScore:2, attendance:null, competition:"Premier League" },
  { date:"2014-12-21", stadium:"St. James' Park", home:"Newcastle United", away:"Sunderland AFC", homeScore:0, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2014-12-06", stadium:"St. James' Park", home:"Newcastle United", away:"Chelsea FC", homeScore:2, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2014-11-22", stadium:"St. James' Park", home:"Newcastle United", away:"Queens Park Rangers", homeScore:1, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2014-11-01", stadium:"St. James' Park", home:"Newcastle United", away:"Liverpool FC", homeScore:1, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2014-10-18", stadium:"St. James' Park", home:"Newcastle United", away:"Leicester City", homeScore:1, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2014-09-20", stadium:"St. James' Park", home:"Newcastle United", away:"Hull City", homeScore:2, awayScore:2, attendance:null, competition:"Premier League" },
  { date:"2014-08-09", stadium:"Brunton Park", home:"Carlisle United", away:"Luton Town", homeScore:0, awayScore:1, attendance:null, competition:"League Two" },
  { date:"2014-05-03", stadium:"St. James' Park", home:"Newcastle United", away:"Cardiff City", homeScore:3, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2014-04-19", stadium:"St. James' Park", home:"Newcastle United", away:"Swansea City", homeScore:1, awayScore:2, attendance:null, competition:"Premier League" },
  { date:"2014-04-05", stadium:"St. James' Park", home:"Newcastle United", away:"Manchester United", homeScore:0, awayScore:4, attendance:null, competition:"Premier League" },
  { date:"2014-03-25", stadium:"St. James' Park", home:"Newcastle United", away:"Everton FC", homeScore:0, awayScore:3, attendance:null, competition:"Premier League" },
  { date:"2014-03-22", stadium:"St. James' Park", home:"Newcastle United", away:"Crystal Palace", homeScore:1, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2014-02-23", stadium:"St. James' Park", home:"Newcastle United", away:"Aston Villa", homeScore:1, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2014-02-12", stadium:"St. James' Park", home:"Newcastle United", away:"Tottenham Hotspur", homeScore:0, awayScore:4, attendance:null, competition:"Premier League" },
  { date:"2014-02-01", stadium:"St. James' Park", home:"Newcastle United", away:"Sunderland AFC", homeScore:0, awayScore:3, attendance:null, competition:"Premier League" },
  { date:"2014-01-12", stadium:"St. James' Park", home:"Newcastle United", away:"Manchester City", homeScore:0, awayScore:2, attendance:null, competition:"Premier League" },
  { date:"2013-12-26", stadium:"St. James' Park", home:"Newcastle United", away:"Stoke City", homeScore:5, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2013-08-27", stadium:"Brunton Park", home:"Carlisle United", away:"Leicester City", homeScore:2, awayScore:5, attendance:null, competition:"League Cup" },
  { date:"2013-08-24", stadium:"St. James' Park", home:"Newcastle United", away:"West Ham United", homeScore:0, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2013-08-17", stadium:"Brunton Park", home:"Carlisle United", away:"Coventry City", homeScore:0, awayScore:4, attendance:null, competition:"League One" },
  { date:"2013-05-19", stadium:"St. James' Park", home:"Newcastle United", away:"Arsenal FC", homeScore:0, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2013-04-27", stadium:"St. James' Park", home:"Newcastle United", away:"Liverpool FC", homeScore:0, awayScore:6, attendance:null, competition:"Premier League" },
  { date:"2013-04-14", stadium:"St. James' Park", home:"Newcastle United", away:"Sunderland AFC", homeScore:0, awayScore:3, attendance:null, competition:"Premier League" },
  { date:"2013-04-11", stadium:"St. James' Park", home:"Newcastle United", away:"SL Benfica", homeScore:1, awayScore:1, attendance:null, competition:"UEFA Europa League Quarter Final" },
  { date:"2013-04-07", stadium:"St. James' Park", home:"Newcastle United", away:"Fulham FC", homeScore:1, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2013-03-14", stadium:"St. James' Park", home:"Newcastle United", away:"Anzhi Makhachkala", homeScore:1, awayScore:0, attendance:null, competition:"UEFA Europa League Round of 16" },
  { date:"2013-03-10", stadium:"St. James' Park", home:"Newcastle United", away:"Stoke City", homeScore:2, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2013-02-24", stadium:"St. James' Park", home:"Newcastle United", away:"Southampton FC", homeScore:4, awayScore:2, attendance:null, competition:"Premier League" },
  { date:"2013-02-14", stadium:"St. James' Park", home:"Newcastle United", away:"FC Metalist Kharkiv", homeScore:0, awayScore:0, attendance:null, competition:"UEFA Europa League Round of 32" },
  { date:"2013-02-02", stadium:"St. James' Park", home:"Newcastle United", away:"Chelsea FC", homeScore:3, awayScore:2, attendance:null, competition:"Premier League" },
  { date:"2013-01-19", stadium:"St. James' Park", home:"Newcastle United", away:"Reading FC", homeScore:1, awayScore:2, attendance:null, competition:"Premier League" },
  { date:"2013-01-02", stadium:"St. James' Park", home:"Newcastle United", away:"Everton FC", homeScore:1, awayScore:2, attendance:null, competition:"Premier League" },
  { date:"2012-12-29", stadium:"John Smith's Stadium", home:"Huddersfield Town", away:"Sheffield Wednesday", homeScore:0, awayScore:0, attendance:null, competition:"Championship" },
  { date:"2012-05-26", stadium:"Wembley Stadium", home:"Huddersfield Town", away:"Sheffield United", homeScore:0, awayScore:0, attendance:null, competition:"League One" },
  { date:"2012-04-01", stadium:"St. James' Park", home:"Newcastle United", away:"Liverpool FC", homeScore:2, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2012-03-31", stadium:"Brunton Park", home:"Carlisle United", away:"Huddersfield Town", homeScore:2, awayScore:1, attendance:null, competition:"League One" },
  { date:"2012-03-18", stadium:"St. James' Park", home:"Newcastle United", away:"Norwich City", homeScore:1, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2012-03-04", stadium:"St. James' Park", home:"Newcastle United", away:"Sunderland AFC", homeScore:1, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2012-02-25", stadium:"St. James' Park", home:"Newcastle United", away:"Wolverhampton Wanderers", homeScore:2, awayScore:2, attendance:null, competition:"Premier League" },
  { date:"2012-02-05", stadium:"St. James' Park", home:"Newcastle United", away:"Aston Villa", homeScore:2, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2012-01-15", stadium:"St. James' Park", home:"Newcastle United", away:"Queens Park Rangers", homeScore:1, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2012-01-07", stadium:"St. James' Park", home:"Newcastle United", away:"Blackburn Rovers", homeScore:2, awayScore:1, attendance:null, competition:"FA Cup" },
  { date:"2012-01-04", stadium:"St. James' Park", home:"Newcastle United", away:"Manchester United", homeScore:3, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2011-11-19", stadium:"Etihad Stadium", home:"Manchester City", away:"Newcastle United", homeScore:3, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2011-10-25", stadium:"Brunton Park", home:"Carlisle United", away:"Sheffield Wednesday", homeScore:3, awayScore:2, attendance:null, competition:"League One" },
  { date:"2011-07-31", stadium:"Elland Road", home:"Leeds United", away:"Newcastle United", homeScore:3, awayScore:2, attendance:20457, competition:"" },
  { date:"2011-05-29", stadium:"Old Trafford", home:"Huddersfield Town", away:"Peterborough United", homeScore:0, awayScore:3, attendance:null, competition:"League One Playoff Final" },
  { date:"2011-05-18", stadium:"John Smith's Stadium", home:"Huddersfield Town", away:"AFC Bournemouth", homeScore:4, awayScore:2, attendance:null, competition:"Playoff" },
  { date:"2011-03-05", stadium:"St. James' Park", home:"Newcastle United", away:"Everton FC", homeScore:1, awayScore:2, attendance:null, competition:"Premier League" },
  { date:"2011-02-26", stadium:"St. James' Park", home:"Newcastle United", away:"Bolton Wanderers", homeScore:1, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2011-02-05", stadium:"St. James' Park", home:"Newcastle United", away:"Arsenal FC", homeScore:4, awayScore:4, attendance:null, competition:"Premier League" },
  { date:"2011-01-22", stadium:"St. James' Park", home:"Newcastle United", away:"Tottenham Hotspur", homeScore:1, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2011-01-05", stadium:"St. James' Park", home:"Newcastle United", away:"West Ham United", homeScore:5, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2010-12-26", stadium:"St. James' Park", home:"Newcastle United", away:"Manchester City", homeScore:1, awayScore:3, attendance:null, competition:"Premier League" },
  { date:"2010-12-11", stadium:"St. James' Park", home:"Newcastle United", away:"Liverpool FC", homeScore:3, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2010-11-28", stadium:"St. James' Park", home:"Newcastle United", away:"Chelsea FC", homeScore:1, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2010-11-13", stadium:"St. James' Park", home:"Newcastle United", away:"Fulham FC", homeScore:0, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2010-11-10", stadium:"St. James' Park", home:"Newcastle United", away:"Blackburn Rovers", homeScore:1, awayScore:2, attendance:null, competition:"Premier League" },
  { date:"2010-10-31", stadium:"St. James' Park", home:"Newcastle United", away:"Sunderland AFC", homeScore:5, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2010-10-27", stadium:"St. James' Park", home:"Newcastle United", away:"Arsenal FC", homeScore:0, awayScore:4, attendance:null, competition:"League Cup 4. Round" },
  { date:"2010-10-16", stadium:"St. James' Park", home:"Newcastle United", away:"Wigan Athletic", homeScore:2, awayScore:2, attendance:null, competition:"Premier League" },
  { date:"2010-10-03", stadium:"Etihad Stadium", home:"Manchester City", away:"Newcastle United", homeScore:2, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2010-09-26", stadium:"St. James' Park", home:"Newcastle United", away:"Stoke City", homeScore:1, awayScore:2, attendance:null, competition:"Premier League" },
  { date:"2010-09-11", stadium:"St. James' Park", home:"Newcastle United", away:"Blackpool FC", homeScore:0, awayScore:2, attendance:null, competition:"Premier League" },
  { date:"2010-08-22", stadium:"St. James' Park", home:"Newcastle United", away:"Aston Villa", homeScore:6, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2010-04-24", stadium:"St. James' Park", home:"Newcastle United", away:"Ipswich Town", homeScore:2, awayScore:2, attendance:null, competition:"Championship" },
  { date:"2010-04-10", stadium:"St. James' Park", home:"Newcastle United", away:"Blackpool FC", homeScore:4, awayScore:1, attendance:null, competition:"Championship" },
  { date:"2010-04-05", stadium:"St. James' Park", home:"Newcastle United", away:"Sheffield United", homeScore:2, awayScore:1, attendance:null, competition:"Championship" },
  { date:"2010-03-29", stadium:"St. James' Park", home:"Newcastle United", away:"Nottingham Forest", homeScore:2, awayScore:0, attendance:null, competition:"Championship" },
  { date:"2010-03-23", stadium:"Eco-Power Stadium", home:"Doncaster Rovers", away:"Newcastle United", homeScore:0, awayScore:1, attendance:null, competition:"Championship" },
  { date:"2010-03-17", stadium:"St. James' Park", home:"Newcastle United", away:"Scunthorpe United", homeScore:3, awayScore:0, attendance:null, competition:"Championship" },
  { date:"2010-02-20", stadium:"St. James' Park", home:"Newcastle United", away:"Preston North End", homeScore:3, awayScore:0, attendance:null, competition:"Championship" },
  { date:"2010-02-17", stadium:"St. James' Park", home:"Newcastle United", away:"Coventry City", homeScore:4, awayScore:1, attendance:null, competition:"Championship" },
  { date:"2010-02-05", stadium:"St. James' Park", home:"Newcastle United", away:"Cardiff City", homeScore:5, awayScore:1, attendance:null, competition:"Championship" },
  { date:"2010-01-27", stadium:"St. James' Park", home:"Newcastle United", away:"Crystal Palace", homeScore:2, awayScore:0, attendance:null, competition:"Championship" },
  { date:"2010-01-18", stadium:"St. James' Park", home:"Newcastle United", away:"West Bromwich Albion", homeScore:2, awayScore:2, attendance:null, competition:"Championship" },
  { date:"2010-01-02", stadium:"John Smith's Stadium", home:"Huddersfield Town", away:"West Bromwich Albion", homeScore:0, awayScore:2, attendance:null, competition:"FA Cup" },
  { date:"2009-12-28", stadium:"St. James' Park", home:"Newcastle United", away:"Derby County", homeScore:0, awayScore:0, attendance:null, competition:"Championship" },
  { date:"2009-12-20", stadium:"St. James' Park", home:"Newcastle United", away:"Middlesbrough FC", homeScore:2, awayScore:0, attendance:null, competition:"Championship" },
  { date:"2009-12-12", stadium:"Oakwell Stadium", home:"Barnsley FC", away:"Newcastle United", homeScore:2, awayScore:2, attendance:null, competition:"Championship" },
  { date:"2009-08-26", stadium:"St. James' Park", home:"Newcastle United", away:"Huddersfield Town", homeScore:4, awayScore:3, attendance:null, competition:"League Cup 2. Round" },
  { date:"2009-01-03", stadium:"John Smith's Stadium", home:"Huddersfield Town", away:"Oldham Athletic", homeScore:1, awayScore:1, attendance:null, competition:"League One" },
  { date:"2008-09-13", stadium:"St. James' Park", home:"Newcastle United", away:"Hull City", homeScore:1, awayScore:2, attendance:null, competition:"Premier League" },
  { date:"2008-08-06", stadium:"John Smith's Stadium", home:"Huddersfield Town", away:"Arsenal FC", homeScore:1, awayScore:2, attendance:null, competition:"Friendly" },
  { date:"2008-03-22", stadium:"St. James' Park", home:"Newcastle United", away:"Fulham FC", homeScore:2, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2008-01-05", stadium:"John Smith's Stadium", home:"Huddersfield Town", away:"Birmingham City", homeScore:2, awayScore:1, attendance:null, competition:"FA Cup" },
  { date:"2006-10-25", stadium:"St. James' Park", home:"Newcastle United", away:"Portsmouth FC", homeScore:3, awayScore:0, attendance:null, competition:"League Cup 3. Round" },
  { date:"2006-02-04", stadium:"St. James' Park", home:"Newcastle United", away:"Portsmouth FC", homeScore:2, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2005-09-10", stadium:"St. James' Park", home:"Newcastle United", away:"Fulham FC", homeScore:1, awayScore:1, attendance:null, competition:"Premier League" },
  { date:"2004-11-07", stadium:"St. James' Park", home:"Newcastle United", away:"Fulham FC", homeScore:1, awayScore:4, attendance:null, competition:"Premier League" },
  { date:"2004-10-27", stadium:"St. James' Park", home:"Newcastle United", away:"Norwich City", homeScore:2, awayScore:1, attendance:null, competition:"League Cup" },
  { date:"2004-07-31", stadium:"St. James' Park", home:"Newcastle United", away:"Rangers FC", homeScore:4, awayScore:2, attendance:null, competition:"The Newcastle Gateshead Cup" },
  { date:"2002-03-26", stadium:"University of Bradford Stadium", home:"England U21", away:"Italy U21", homeScore:1, awayScore:1, attendance:null, competition:"" },
  { date:"2001-05-06", stadium:"John Smith's Stadium", home:"Huddersfield Town", away:"Birmingham City", homeScore:1, awayScore:2, attendance:null, competition:"First Division" },
];
