// ─── Hawkbology: Updated match data from Futbology CSV ─────────────────
// Format: { date, stadium, home, away, homeScore, awayScore, attendance, competition }
const INITIAL_MATCHES = [
  { date:"2026-09-19", stadium:"Ashton Athletic Track", home:"Woodford Town FC", away:"Mulbarton Wanderers", homeScore:1, awayScore:2, attendance:null, competition:"FA Cup Qualification" },
  { date:"2026-09-11", stadium:"Mounthawk Park", home:"Kerry FC (Ireland)", away:"Bray Wanderers FC", homeScore:0, awayScore:1, attendance:null, competition:"League of Ireland First Division" },
  { date:"2026-09-07", stadium:"War Memorial Sports Ground (Carshalton)", home:"Carshalton Athletic FC", away:"Chertsey Town FC", homeScore:1, awayScore:2, attendance:null, competition:"FA Cup Qualification" },
  { date:"2026-09-05", stadium:"Bet365 Stadium", home:"Stoke City", away:"Charlton Athletic", homeScore:4, awayScore:0, attendance:null, competition:"Championship" },
  { date:"2026-08-29", stadium:"Cledara Abbey Stadium", home:"Cambridge United", away:"Huddersfield Town", homeScore:1, awayScore:2, attendance:null, competition:"League One" },
  { date:"2026-08-25", stadium:"Hillsborough Stadium", home:"Sheffield Wednesday", away:"Wolverhampton Wanderers", homeScore:0, awayScore:2, attendance:null, competition:"EFL Cup 2. Round" },
  { date:"2026-08-23", stadium:"St. James' Park", home:"Newcastle United", away:"Liverpool FC", homeScore:2, awayScore:2, attendance:null, competition:"Premier League" },
  { date:"2026-08-22", stadium:"Butcher's Arms Ground", home:"Droylsden FC", away:"Garforth Town AFC", homeScore:1, awayScore:2, attendance:null, competition:"FA Cup Qualification" },
  { date:"2026-08-22", stadium:"Peninsula Stadium", home:"Salford City FC", away:"Chesterfield FC", homeScore:0, awayScore:1, attendance:null, competition:"League Two" },
  { date:"2026-08-14", stadium:"Coventry Building Society Arena", home:"Coventry City", away:"AS Monaco", homeScore:2, awayScore:0, attendance:null, competition:"Friendly" },
  { date:"2026-08-11", stadium:"Capershotts", home:"Waltham Abbey FC", away:"Potters Bar Town FC", homeScore:2, awayScore:4, attendance:null, competition:"Southern League Division One Central" },
  { date:"2026-08-08", stadium:"Roding Lane", home:"Buckhurst Hill FC", away:"Barking FC", homeScore:2, awayScore:0, attendance:null, competition:"FA Cup Extra Qualification" },
  { date:"2026-08-01", stadium:"Princes Park (Dartford)", home:"Dartford FC", away:"Ashford United", homeScore:4, awayScore:0, attendance:null, competition:"Friendly" },
  { date:"2026-07-25", stadium:"Loftus Road", home:"Queens Park Rangers", away:"ACF Fiorentina", homeScore:3, awayScore:2, attendance:null, competition:"Friendly" },
  { date:"2026-07-22", stadium:"The Cherry Red Records Stadium", home:"AFC Wimbledon", away:"Norwich City", homeScore:0, awayScore:0, attendance:null, competition:"Friendly" },
  { date:"2026-07-21", stadium:"Roding Lane", home:"Buckhurst Hill FC", away:"Waltham Abbey FC", homeScore:2, awayScore:1, attendance:null, competition:"Friendly" },
  { date:"2026-07-18", stadium:"Flamingo Park", home:"Cray Wanderers FC", away:"Tonbridge Angels", homeScore:1, awayScore:0, attendance:null, competition:"Friendly" },
  { date:"2026-07-18", stadium:"St Paul's Sports Ground", home:"Fisher FC", away:"Grays Athletic FC", homeScore:2, awayScore:3, attendance:null, competition:"Friendly" },
  { date:"2026-07-11", stadium:"Woodside Park", home:"Bishop's Stortford FC", away:"Chelmsford City", homeScore:1, awayScore:3, attendance:null, competition:"Friendly" },
  { date:"2026-07-04", stadium:"Barnet Lane 3G", home:"Wingate & Finchley FC", away:"Royston Town FC", homeScore:0, awayScore:2, attendance:null, competition:"Friendly" },
  { date:"2026-05-25", stadium:"Wembley Stadium", home:"Notts County", away:"Salford City FC", homeScore:3, awayScore:0, attendance:null, competition:"League Two Play-off Final" },
  { date:"2026-05-24", stadium:"Wembley Stadium", home:"Bolton Wanderers", away:"Stockport County", homeScore:4, awayScore:1, attendance:null, competition:"League One Play-off Final" },
  { date:"2026-05-10", stadium:"Wembley Stadium", home:"Boreham Wood FC", away:"Rochdale AFC", homeScore:2, awayScore:2, attendance:null, competition:"National League Play-off Final" },
  { date:"2026-05-02", stadium:"Priestfield Stadium", home:"Gillingham FC", away:"Shrewsbury Town", homeScore:1, awayScore:0, attendance:null, competition:"League Two" },
  { date:"2026-04-14", stadium:"Wembley Stadium", home:"England (W)", away:"Spain (W)", homeScore:1, awayScore:0, attendance:null, competition:"Women's World Championship Qualification" },
  { date:"2026-04-06", stadium:"Brisbane Road", home:"Leyton Orient", away:"Huddersfield Town", homeScore:1, awayScore:2, attendance:null, competition:"League One" },
  { date:"2026-04-01", stadium:"Stamford Bridge", home:"Chelsea FC Women", away:"Arsenal Women FC", homeScore:1, awayScore:0, attendance:null, competition:"UEFA Women's Champions League Quarter Final" },
  { date:"2026-03-21", stadium:"Emirates Stadium", home:"Arsenal Women FC", away:"West Ham United Women", homeScore:5, awayScore:0, attendance:null, competition:"Women's Super League" },
  { date:"2026-03-21", stadium:"Coles Park Stadium", home:"Haringey Borough", away:"Winslow United", homeScore:2, awayScore:1, attendance:null, competition:"Spartan South Midlands Premier Division" },
  { date:"2026-03-16", stadium:"Academy Stadium", home:"Manchester City U21", away:"Liverpool FC U21", homeScore:2, awayScore:0, attendance:null, competition:"Premier League 2" },
  { date:"2026-03-14", stadium:"Skye Direct Stadium", home:"Golcar United", away:"Penistone Church FC", homeScore:2, awayScore:0, attendance:null, competition:"Northern Counties East Premier Division" },
  { date:"2026-03-11", stadium:"The Hawthorns", home:"West Bromwich Albion", away:"Southampton FC", homeScore:1, awayScore:1, attendance:null, competition:"Championship" },
  { date:"2026-03-09", stadium:"London Stadium", home:"West Ham United", away:"Brentford FC", homeScore:2, awayScore:2, attendance:null, competition:"FA Cup" },
  { date:"2026-03-07", stadium:"Stadium MK", home:"Milton Keynes Dons", away:"Harrogate Town", homeScore:4, awayScore:1, attendance:null, competition:"League Two" },
  { date:"2026-02-21", stadium:"London Stadium", home:"West Ham United", away:"AFC Bournemouth", homeScore:0, awayScore:0, attendance:null, competition:"Premier League" },
  { date:"2026-02-08", stadium:"Emirates Stadium", home:"Arsenal Women FC", away:"Manchester City Women", homeScore:1, awayScore:0, attendance:null, competition:"Women's Super League" },
  { date:"2026-02-07", stadium:"Jack Carter Centre 3G", home:"Frenford FC", away:"Benfleet FC", homeScore:2, awayScore:5, attendance:null, competition:"Essex Senior Football League" },
  { date:"2026-01-30", stadium:"Ashton Gate", home:"Bristol City", away:"Derby County", homeScore:0, awayScore:5, attendance:null, competition:"Championship" },
  { date:"2026-01-28", stadium:"Gtech Community Stadium", home:"Corinthians Feminino", away:"Gotham FC", homeScore:1, awayScore:0, attendance:null, competition:"Women's Champions Cup Semi Final" },
  { date:"2026-01-28", stadium:"Gtech Community Stadium", home:"Arsenal Women FC", away:"AS FAR", homeScore:6, awayScore:0, attendance:null, competition:"Women's Champions Cup Semi Final" },
  { date:"2026-01-17", stadium:"Parsloes Park 3G", home:"Waltham Forest Borough", away:"Woodford Town U23", homeScore:1, awayScore:1, attendance:null, competition:"Essex Saturday Premier Cup" },
  { date:"2026-01-17", stadium:"Parsloes Park 3G", home:"Athletic Newham FC", away:"Little Oakley", homeScore:1, awayScore:1, attendance:null, competition:"Essex Senior Football League" },
  { date:"2026-01-11", stadium:"Brisbane Road", home:"Tottenham Hotspur Women", away:"Leicester City Women", homeScore:1, awayScore:0, attendance:null, competition:"Women's Super League" },
  { date:"2026-01-11", stadium:"London Stadium", home:"West Ham United", away:"Queens Park Rangers", homeScore:2, awayScore:1, attendance:null, competition:"FA Cup" },
  { date:"2026-01-10", stadium:"Hill Dickinson Stadium", home:"Everton FC", away:"Sunderland AFC", homeScore:1, awayScore:1, attendance:null, competition:"FA Cup" },
  { date:"2025-12-29", stadium:"Melbourne Stadium", home:"Chelmsford City", away:"Dagenham and Redbridge", homeScore:1, awayScore:4, attendance:null, competition:"National League South" },
  { date:"2025-12-27", stadium:"Wombwell Recreation Ground", home:"Wombwell Town", away:"Golcar United", homeScore:1, awayScore:1, attendance:null, competition:"Northern Counties East Premier Division" },
  { date:"2025-12-26", stadium:"John Smith's Stadium", home:"Huddersfield Town", away:"Port Vale", homeScore:5, awayScore:0, attendance:null, competition:"League One" },
  { date:"2025-12-06", stadium:"Melbourne Stadium", home:"Chelmsford City", away:"Weston-super-Mare AFC", homeScore:0, awayScore:2, attendance:null, competition:"FA Cup" },
  { date:"2025-11-29", stadium:"Wembley Stadium", home:"England (W)", away:"China (W)", homeScore:8, awayScore:0, attendance:null, competition:"Friendly" },
  { date:"2019-10-29", stadium:"Coles Park Stadium", home:"Haringey Borough", away:"Yeovil Town", homeScore:0, awayScore:3, attendance:null, competition:"FA Cup Qualification" }
];