// Hawk Football Travels — Stadium & Club Data
// English clubs: Premier League down to Step 6 (National League North/South and Regional Divisions)
// Plus a European section

const ENGLISH_CLUBS = [
  // ── Premier League ──
  { id: 'arsenal', name: 'Arsenal', stadium: 'Emirates Stadium', tier: 1, league: 'Premier League', city: 'London', region: 'england' },
  { id: 'aston-villa', name: 'Aston Villa', stadium: 'Villa Park', tier: 1, league: 'Premier League', city: 'Birmingham', region: 'england' },
  { id: 'bournemouth', name: 'AFC Bournemouth', stadium: 'Vitality Stadium', tier: 1, league: 'Premier League', city: 'Bournemouth', region: 'england' },
  { id: 'brentford', name: 'Brentford', stadium: 'Gtech Community Stadium', tier: 1, league: 'Premier League', city: 'London', region: 'england' },
  { id: 'brighton', name: 'Brighton & Hove Albion', stadium: 'Amex Stadium', tier: 1, league: 'Premier League', city: 'Brighton', region: 'england' },
  { id: 'chelsea', name: 'Chelsea', stadium: 'Stamford Bridge', tier: 1, league: 'Premier League', city: 'London', region: 'england' },
  { id: 'crystal-palace', name: 'Crystal Palace', stadium: 'Selhurst Park', tier: 1, league: 'Premier League', city: 'London', region: 'england' },
  { id: 'everton', name: 'Everton', stadium: 'Goodison Park', tier: 1, league: 'Premier League', city: 'Liverpool', region: 'england' },
  { id: 'fulham', name: 'Fulham', stadium: 'Craven Cottage', tier: 1, league: 'Premier League', city: 'London', region: 'england' },
  { id: 'ipswich', name: 'Ipswich Town', stadium: 'Portman Road', tier: 1, league: 'Premier League', city: 'Ipswich', region: 'england' },
  { id: 'leicester', name: 'Leicester City', stadium: 'King Power Stadium', tier: 1, league: 'Premier League', city: 'Leicester', region: 'england' },
  { id: 'liverpool', name: 'Liverpool', stadium: 'Anfield', tier: 1, league: 'Premier League', city: 'Liverpool', region: 'england' },
  { id: 'man-city', name: 'Manchester City', stadium: 'Etihad Stadium', tier: 1, league: 'Premier League', city: 'Manchester', region: 'england' },
  { id: 'man-utd', name: 'Manchester United', stadium: 'Old Trafford', tier: 1, league: 'Premier League', city: 'Manchester', region: 'england' },
  { id: 'newcastle', name: 'Newcastle United', stadium: "St. James' Park", tier: 1, league: 'Premier League', city: 'Newcastle', region: 'england' },
  { id: 'nottm-forest', name: 'Nottingham Forest', stadium: 'City Ground', tier: 1, league: 'Premier League', city: 'Nottingham', region: 'england' },
  { id: 'southampton', name: 'Southampton', stadium: "St. Mary's Stadium", tier: 1, league: 'Premier League', city: 'Southampton', region: 'england' },
  { id: 'spurs', name: 'Tottenham Hotspur', stadium: 'Tottenham Hotspur Stadium', tier: 1, league: 'Premier League', city: 'London', region: 'england' },
  { id: 'west-ham', name: 'West Ham United', stadium: 'London Stadium', tier: 1, league: 'Premier League', city: 'London', region: 'england' },
  { id: 'wolves', name: 'Wolverhampton Wanderers', stadium: 'Molineux', tier: 1, league: 'Premier League', city: 'Wolverhampton', region: 'england' },

  // ── Championship ──
  { id: 'blackburn', name: 'Blackburn Rovers', stadium: 'Ewood Park', tier: 2, league: 'Championship', city: 'Blackburn', region: 'england' },
  { id: 'bristol-city', name: 'Bristol City', stadium: 'Ashton Gate', tier: 2, league: 'Championship', city: 'Bristol', region: 'england' },
  { id: 'burnley', name: 'Burnley', stadium: 'Turf Moor', tier: 2, league: 'Championship', city: 'Burnley', region: 'england' },
  { id: 'cardiff', name: 'Cardiff City', stadium: 'Cardiff City Stadium', tier: 2, league: 'Championship', city: 'Cardiff', region: 'wales' },
  { id: 'coventry', name: 'Coventry City', stadium: 'Coventry Building Society Arena', tier: 2, league: 'Championship', city: 'Coventry', region: 'england' },
  { id: 'derby', name: 'Derby County', stadium: 'Pride Park', tier: 2, league: 'Championship', city: 'Derby', region: 'england' },
  { id: 'hull', name: 'Hull City', stadium: 'MKM Stadium', tier: 2, league: 'Championship', city: 'Hull', region: 'england' },
  { id: 'leeds', name: 'Leeds United', stadium: 'Elland Road', tier: 2, league: 'Championship', city: 'Leeds', region: 'england' },
  { id: 'luton', name: 'Luton Town', stadium: 'Kenilworth Road', tier: 2, league: 'Championship', city: 'Luton', region: 'england' },
  { id: 'middlesbrough', name: 'Middlesbrough', stadium: 'Riverside Stadium', tier: 2, league: 'Championship', city: 'Middlesbrough', region: 'england' },
  { id: 'millwall', name: 'Millwall', stadium: 'The Den', tier: 2, league: 'Championship', city: 'London', region: 'england' },
  { id: 'norwich', name: 'Norwich City', stadium: 'Carrow Road', tier: 2, league: 'Championship', city: 'Norwich', region: 'england' },
  { id: 'oxford', name: 'Oxford United', stadium: "Kassam Stadium", tier: 2, league: 'Championship', city: 'Oxford', region: 'england' },
  { id: 'plymouth', name: 'Plymouth Argyle', stadium: 'Home Park', tier: 2, league: 'Championship', city: 'Plymouth', region: 'england' },
  { id: 'portsmouth', name: 'Portsmouth', stadium: 'Fratton Park', tier: 2, league: 'Championship', city: 'Portsmouth', region: 'england' },
  { id: 'preston', name: 'Preston North End', stadium: 'Deepdale', tier: 2, league: 'Championship', city: 'Preston', region: 'england' },
  { id: 'qpr', name: 'QPR', stadium: 'Loftus Road', tier: 2, league: 'Championship', city: 'London', region: 'england' },
  { id: 'sheffield-utd', name: 'Sheffield United', stadium: 'Bramall Lane', tier: 2, league: 'Championship', city: 'Sheffield', region: 'england' },
  { id: 'stoke', name: 'Stoke City', stadium: 'bet365 Stadium', tier: 2, league: 'Championship', city: 'Stoke-on-Trent', region: 'england' },
  { id: 'sunderland', name: 'Sunderland', stadium: 'Stadium of Light', tier: 2, league: 'Championship', city: 'Sunderland', region: 'england' },
  { id: 'swansea', name: 'Swansea City', stadium: 'Swansea.com Stadium', tier: 2, league: 'Championship', city: 'Swansea', region: 'wales' },
  { id: 'watford', name: 'Watford', stadium: 'Vicarage Road', tier: 2, league: 'Championship', city: 'Watford', region: 'england' },
  { id: 'west-brom', name: 'West Bromwich Albion', stadium: 'The Hawthorns', tier: 2, league: 'Championship', city: 'West Bromwich', region: 'england' },
  { id: 'wigan', name: 'Wigan Athletic', stadium: 'DW Stadium', tier: 2, league: 'Championship', city: 'Wigan', region: 'england' },

  // ── League One ──
  { id: 'barnsley', name: 'Barnsley', stadium: 'Oakwell', tier: 3, league: 'League One', city: 'Barnsley', region: 'england' },
  { id: 'birmingham', name: 'Birmingham City', stadium: 'St. Andrew\'s', tier: 3, league: 'League One', city: 'Birmingham', region: 'england' },
  { id: 'blackpool', name: 'Blackpool', stadium: 'Bloomfield Road', tier: 3, league: 'League One', city: 'Blackpool', region: 'england' },
  { id: 'bolton', name: 'Bolton Wanderers', stadium: 'Toughsheet Community Stadium', tier: 3, league: 'League One', city: 'Bolton', region: 'england' },
  { id: 'bristol-rovers', name: 'Bristol Rovers', stadium: 'Memorial Stadium', tier: 3, league: 'League One', city: 'Bristol', region: 'england' },
  { id: 'burton', name: 'Burton Albion', stadium: 'Pirelli Stadium', tier: 3, league: 'League One', city: 'Burton upon Trent', region: 'england' },
  { id: 'cambridge', name: 'Cambridge United', stadium: 'Abbey Stadium', tier: 3, league: 'League One', city: 'Cambridge', region: 'england' },
  { id: 'charlton', name: 'Charlton Athletic', stadium: 'The Valley', tier: 3, league: 'League One', city: 'London', region: 'england' },
  { id: 'chesterfield', name: 'Chesterfield', stadium: 'SMH Group Stadium', tier: 3, league: 'League One', city: 'Chesterfield', region: 'england' },
  { id: 'exeter', name: 'Exeter City', stadium: 'St James Park', tier: 3, league: 'League One', city: 'Exeter', region: 'england' },
  { id: 'huddersfield', name: 'Huddersfield Town', stadium: 'John Smith\'s Stadium', tier: 3, league: 'League One', city: 'Huddersfield', region: 'england' },
  { id: 'leyton-orient', name: 'Leyton Orient', stadium: 'Brisbane Road', tier: 3, league: 'League One', city: 'London', region: 'england' },
  { id: 'lincoln', name: 'Lincoln City', stadium: 'LNER Stadium', tier: 3, league: 'League One', city: 'Lincoln', region: 'england' },
  { id: 'northampton', name: 'Northampton Town', stadium: 'PTS Academy Stadium', tier: 3, league: 'League One', city: 'Northampton', region: 'england' },
  { id: 'peterborough', name: 'Peterborough United', stadium: 'London Road', tier: 3, league: 'League One', city: 'Peterborough', region: 'england' },
  { id: 'reading', name: 'Reading', stadium: 'Select Car Leasing Stadium', tier: 3, league: 'League One', city: 'Reading', region: 'england' },
  { id: 'rotherham', name: 'Rotherham United', stadium: 'AESSEAL New York Stadium', tier: 3, league: 'League One', city: 'Rotherham', region: 'england' },
  { id: 'shrewsbury', name: 'Shrewsbury Town', stadium: 'Montgomery Waters Meadow', tier: 3, league: 'League One', city: 'Shrewsbury', region: 'england' },
  { id: 'stevenage', name: 'Stevenage', stadium: 'Lamex Stadium', tier: 3, league: 'League One', city: 'Stevenage', region: 'england' },
  { id: 'stockport', name: 'Stockport County', stadium: 'Edgeley Park', tier: 3, league: 'League One', city: 'Stockport', region: 'england' },
  { id: 'wycombe', name: 'Wycombe Wanderers', stadium: 'Adams Park', tier: 3, league: 'League One', city: 'High Wycombe', region: 'england' },

  // ── League Two ──
  { id: 'accrington', name: 'Accrington Stanley', stadium: 'Crown Ground', tier: 4, league: 'League Two', city: 'Accrington', region: 'england' },
  { id: 'barrow', name: 'Barrow', stadium: 'Holker Street', tier: 4, league: 'League Two', city: 'Barrow-in-Furness', region: 'england' },
  { id: 'bradford-city', name: 'Bradford City', stadium: 'Valley Parade', tier: 4, league: 'League Two', city: 'Bradford', region: 'england' },
  { id: 'carlisle', name: 'Carlisle United', stadium: 'Brunton Park', tier: 4, league: 'League Two', city: 'Carlisle', region: 'england' },
  { id: 'cheltenham', name: 'Cheltenham Town', stadium: 'Jonny-Rocks Stadium', tier: 4, league: 'League Two', city: 'Cheltenham', region: 'england' },
  { id: 'colchester', name: 'Colchester United', stadium: 'JobServe Community Stadium', tier: 4, league: 'League Two', city: 'Colchester', region: 'england' },
  { id: 'crawley', name: 'Crawley Town', stadium: 'Broadfield Stadium', tier: 4, league: 'League Two', city: 'Crawley', region: 'england' },
  { id: 'crewe', name: 'Crewe Alexandra', stadium: 'Alexandra Stadium', tier: 4, league: 'League Two', city: 'Crewe', region: 'england' },
  { id: 'doncaster', name: 'Doncaster Rovers', stadium: 'Eco-Power Stadium', tier: 4, league: 'League Two', city: 'Doncaster', region: 'england' },
  { id: 'fleetwood', name: 'Fleetwood Town', stadium: 'Highbury Stadium', tier: 4, league: 'League Two', city: 'Fleetwood', region: 'england' },
  { id: 'gillingham', name: 'Gillingham', stadium: 'MEMS Priestfield Stadium', tier: 4, league: 'League Two', city: 'Gillingham', region: 'england' },
  { id: 'grimsby', name: 'Grimsby Town', stadium: 'Blundell Park', tier: 4, league: 'League Two', city: 'Grimsby', region: 'england' },
  { id: 'harrogate', name: 'Harrogate Town', stadium: 'EnviroVent Stadium', tier: 4, league: 'League Two', city: 'Harrogate', region: 'england' },
  { id: 'mansfield', name: 'Mansfield Town', stadium: 'One Call Stadium', tier: 4, league: 'League Two', city: 'Mansfield', region: 'england' },
  { id: 'mk-dons', name: 'MK Dons', stadium: 'Stadium MK', tier: 4, league: 'League Two', city: 'Milton Keynes', region: 'england' },
  { id: 'morecambe', name: 'Morecambe', stadium: 'Mazuma Mobile Stadium', tier: 4, league: 'League Two', city: 'Morecambe', region: 'england' },
  { id: 'newport', name: 'Newport County', stadium: 'Rodney Parade', tier: 4, league: 'League Two', city: 'Newport', region: 'wales' },
  { id: 'notts-county', name: 'Notts County', stadium: 'Meadow Lane', tier: 4, league: 'League Two', city: 'Nottingham', region: 'england' },
  { id: 'port-vale', name: 'Port Vale', stadium: 'Vale Park', tier: 4, league: 'League Two', city: 'Burslem', region: 'england' },
  { id: 'salford', name: 'Salford City', stadium: 'Peninsula Stadium', tier: 4, league: 'League Two', city: 'Salford', region: 'england' },
  { id: 'swindon', name: 'Swindon Town', stadium: 'County Ground', tier: 4, league: 'League Two', city: 'Swindon', region: 'england' },
  { id: 'tranmere', name: 'Tranmere Rovers', stadium: 'Prenton Park', tier: 4, league: 'League Two', city: 'Birkenhead', region: 'england' },
  { id: 'walsall', name: 'Walsall', stadium: 'Poundland Bescot Stadium', tier: 4, league: 'League Two', city: 'Walsall', region: 'england' },
  { id: 'wrexham', name: 'Wrexham', stadium: 'Racecourse Ground', tier: 4, league: 'League Two', city: 'Wrexham', region: 'wales' },

  // ── National League (Step 5) ──
  { id: 'aldershot', name: 'Aldershot Town', stadium: 'EBB Stadium', tier: 5, league: 'National League', city: 'Aldershot', region: 'england' },
  { id: 'altrincham', name: 'Altrincham', stadium: 'J.Davidson Stadium', tier: 5, league: 'National League', city: 'Altrincham', region: 'england' },
  { id: 'boreham-wood', name: 'Boreham Wood', stadium: 'Meadow Park', tier: 5, league: 'National League', city: 'Boreham Wood', region: 'england' },
  { id: 'bromley', name: 'Bromley', stadium: 'Hayes Lane', tier: 5, league: 'National League', city: 'Bromley', region: 'england' },
  { id: 'chester', name: 'Chester', stadium: 'Deva Stadium', tier: 5, league: 'National League', city: 'Chester', region: 'england' },
  { id: 'dagenham', name: 'Dagenham & Redbridge', stadium: 'Victoria Road', tier: 5, league: 'National League', city: 'Dagenham', region: 'england' },
  { id: 'eastleigh', name: 'Eastleigh', stadium: 'Silverlake Stadium', tier: 5, league: 'National League', city: 'Eastleigh', region: 'england' },
  { id: 'fc-halifax', name: 'FC Halifax Town', stadium: 'The Shay', tier: 5, league: 'National League', city: 'Halifax', region: 'england' },
  { id: 'gateshead', name: 'Gateshead', stadium: 'Gateshead International Stadium', tier: 5, league: 'National League', city: 'Gateshead', region: 'england' },
  { id: 'kidderminster', name: 'Kidderminster Harriers', stadium: 'Aggborough Stadium', tier: 5, league: 'National League', city: 'Kidderminster', region: 'england' },
  { id: 'maidstone', name: 'Maidstone United', stadium: 'Gallagher Stadium', tier: 5, league: 'National League', city: 'Maidstone', region: 'england' },
  { id: 'oldham', name: 'Oldham Athletic', stadium: 'Boundary Park', tier: 5, league: 'National League', city: 'Oldham', region: 'england' },
  { id: 'rochdale', name: 'Rochdale', stadium: 'Crown Oil Arena', tier: 5, league: 'National League', city: 'Rochdale', region: 'england' },
  { id: 'southend', name: 'Southend United', stadium: 'Roots Hall', tier: 5, league: 'National League', city: 'Southend-on-Sea', region: 'england' },
  { id: 'torquay', name: 'Torquay United', stadium: 'Plainmoor', tier: 5, league: 'National League', city: 'Torquay', region: 'england' },
  { id: 'woking', name: 'Woking', stadium: 'Kingfield Stadium', tier: 5, league: 'National League', city: 'Woking', region: 'england' },
  { id: 'york-city', name: 'York City', stadium: 'LNER Community Stadium', tier: 5, league: 'National League', city: 'York', region: 'england' },

  // ── National League North (Step 6) ──
  { id: 'AFC-fylde', name: 'AFC Fylde', stadium: 'Mill Farm', tier: 6, league: 'National League North', city: 'Wesham', region: 'england' },
  { id: 'blyth', name: 'Blyth Spartans', stadium: 'Croft Park', tier: 6, league: 'National League North', city: 'Blyth', region: 'england' },
  { id: 'bradford-pa', name: 'Bradford Park Avenue', stadium: 'Horsfall Stadium', tier: 6, league: 'National League North', city: 'Bradford', region: 'england' },
  { id: 'curzon-ashton', name: 'Curzon Ashton', stadium: 'Tameside Stadium', tier: 6, league: 'National League North', city: 'Ashton-under-Lyne', region: 'england' },
  { id: 'farsley', name: 'Farsley Celtic', stadium: 'Throstle Nest', tier: 6, league: 'National League North', city: 'Farsley', region: 'england' },
  { id: 'fc-united', name: 'FC United of Manchester', stadium: 'Broadhurst Park', tier: 6, league: 'National League North', city: 'Manchester', region: 'england' },
  { id: 'guiseley', name: 'Guiseley', stadium: 'Nethermoor Park', tier: 6, league: 'National League North', city: 'Guiseley', region: 'england' },
  { id: 'hereford', name: 'Hereford', stadium: 'Edgar Street', tier: 6, league: 'National League North', city: 'Hereford', region: 'england' },
  { id: 'kettering', name: 'Kettering Town', stadium: 'Latimer Park', tier: 6, league: 'National League North', city: 'Kettering', region: 'england' },
  { id: 'nantwich', name: 'Nantwich Town', stadium: 'Weaver Stadium', tier: 6, league: 'National League North', city: 'Nantwich', region: 'england' },
  { id: 'scarborough', name: 'Scarborough Athletic', stadium: 'Flamingo Land Stadium', tier: 6, league: 'National League North', city: 'Scarborough', region: 'england' },
  { id: 'spennymoor', name: 'Spennymoor Town', stadium: 'Brewery Field', tier: 6, league: 'National League North', city: 'Spennymoor', region: 'england' },
  { id: 'warrington', name: 'Warrington Rylands', stadium: 'Warrington Sports Club', tier: 6, league: 'National League North', city: 'Warrington', region: 'england' },

  // ── National League South (Step 6) ──
  { id: 'bath', name: 'Bath City', stadium: 'Twerton Park', tier: 6, league: 'National League South', city: 'Bath', region: 'england' },
  { id: 'billericay', name: 'Billericay Town', stadium: 'AGP Arena', tier: 6, league: 'National League South', city: 'Billericay', region: 'england' },
  { id: 'braintree', name: 'Braintree Town', stadium: 'Cressing Road', tier: 6, league: 'National League South', city: 'Braintree', region: 'england' },
  { id: 'dartford', name: 'Dartford', stadium: 'Princes Park', tier: 6, league: 'National League South', city: 'Dartford', region: 'england' },
  { id: 'dover', name: 'Dover Athletic', stadium: 'Crabble Athletic Ground', tier: 6, league: 'National League South', city: 'Dover', region: 'england' },
  { id: 'dulwich', name: 'Dulwich Hamlet', stadium: 'Champion Hill', tier: 6, league: 'National League South', city: 'London', region: 'england' },
  { id: 'ebbsfleet', name: 'Ebbsfleet United', stadium: 'Stonebridge Road', tier: 6, league: 'National League South', city: 'Northfleet', region: 'england' },
  { id: 'hampton', name: 'Hampton & Richmond Borough', stadium: 'Beveree Stadium', tier: 6, league: 'National League South', city: 'Hampton', region: 'england' },
  { id: 'havant', name: 'Havant & Waterlooville', stadium: 'Westleigh Park', tier: 6, league: 'National League South', city: 'Havant', region: 'england' },
  { id: 'hemel', name: 'Hemel Hempstead Town', stadium: 'Vauxhall Road', tier: 6, league: 'National League South', city: 'Hemel Hempstead', region: 'england' },
  { id: 'slough', name: 'Slough Town', stadium: 'Arbour Park', tier: 6, league: 'National League South', city: 'Slough', region: 'england' },
  { id: 'tonbridge', name: 'Tonbridge Angels', stadium: 'Longmead Stadium', tier: 6, league: 'National League South', city: 'Tonbridge', region: 'england' },
  { id: 'truro', name: 'Truro City', stadium: 'Treyew Road', tier: 6, league: 'National League South', city: 'Truro', region: 'england' },
  { id: 'worthing', name: 'Worthing', stadium: 'Woodside Road', tier: 6, league: 'National League South', city: 'Worthing', region: 'england' },
];

const EUROPEAN_CLUBS = [
  // Spain
  { id: 'barcelona', name: 'FC Barcelona', stadium: 'Spotify Camp Nou', country: 'Spain', city: 'Barcelona', region: 'europe' },
  { id: 'real-madrid', name: 'Real Madrid', stadium: 'Santiago Bernabéu', country: 'Spain', city: 'Madrid', region: 'europe' },
  { id: 'atletico-madrid', name: 'Atlético de Madrid', stadium: 'Metropolitano', country: 'Spain', city: 'Madrid', region: 'europe' },
  { id: 'sevilla', name: 'Sevilla FC', stadium: 'Ramón Sánchez-Pizjuán', country: 'Spain', city: 'Seville', region: 'europe' },
  { id: 'real-sociedad', name: 'Real Sociedad', stadium: 'Reale Arena', country: 'Spain', city: 'San Sebastián', region: 'europe' },
  { id: 'athletic-bilbao', name: 'Athletic Club', stadium: 'San Mamés', country: 'Spain', city: 'Bilbao', region: 'europe' },
  { id: 'valencia', name: 'Valencia CF', stadium: 'Mestalla', country: 'Spain', city: 'Valencia', region: 'europe' },
  { id: 'villarreal', name: 'Villarreal CF', stadium: 'Estadio de la Cerámica', country: 'Spain', city: 'Villarreal', region: 'europe' },
  // Germany
  { id: 'bayern', name: 'Bayern München', stadium: 'Allianz Arena', country: 'Germany', city: 'Munich', region: 'europe' },
  { id: 'dortmund', name: 'Borussia Dortmund', stadium: 'Signal Iduna Park', country: 'Germany', city: 'Dortmund', region: 'europe' },
  { id: 'leverkusen', name: 'Bayer Leverkusen', stadium: 'BayArena', country: 'Germany', city: 'Leverkusen', region: 'europe' },
  { id: 'rb-leipzig', name: 'RB Leipzig', stadium: 'Red Bull Arena', country: 'Germany', city: 'Leipzig', region: 'europe' },
  { id: 'frankfurt', name: 'Eintracht Frankfurt', stadium: 'Deutsche Bank Park', country: 'Germany', city: 'Frankfurt', region: 'europe' },
  { id: 'schalke', name: 'Schalke 04', stadium: 'Veltins-Arena', country: 'Germany', city: 'Gelsenkirchen', region: 'europe' },
  { id: 'wolfsburg', name: 'VfL Wolfsburg', stadium: 'Volkswagen Arena', country: 'Germany', city: 'Wolfsburg', region: 'europe' },
  { id: 'freiburg', name: 'SC Freiburg', stadium: 'Europa-Park Stadion', country: 'Germany', city: 'Freiburg', region: 'europe' },
  // Italy
  { id: 'juventus', name: 'Juventus', stadium: 'Allianz Stadium', country: 'Italy', city: 'Turin', region: 'europe' },
  { id: 'ac-milan', name: 'AC Milan', stadium: 'San Siro', country: 'Italy', city: 'Milan', region: 'europe' },
  { id: 'inter-milan', name: 'Inter Milan', stadium: 'San Siro', country: 'Italy', city: 'Milan', region: 'europe' },
  { id: 'napoli', name: 'SSC Napoli', stadium: 'Diego Armando Maradona', country: 'Italy', city: 'Naples', region: 'europe' },
  { id: 'as-roma', name: 'AS Roma', stadium: 'Olimpico', country: 'Italy', city: 'Rome', region: 'europe' },
  { id: 'lazio', name: 'SS Lazio', stadium: 'Olimpico', country: 'Italy', city: 'Rome', region: 'europe' },
  { id: 'atalanta', name: 'Atalanta', stadium: 'Gewiss Stadium', country: 'Italy', city: 'Bergamo', region: 'europe' },
  { id: 'fiorentina', name: 'Fiorentina', stadium: 'Artemio Franchi', country: 'Italy', city: 'Florence', region: 'europe' },
  // France
  { id: 'psg', name: 'Paris Saint-Germain', stadium: 'Parc des Princes', country: 'France', city: 'Paris', region: 'europe' },
  { id: 'monaco', name: 'AS Monaco', stadium: 'Stade Louis II', country: 'Monaco', city: 'Monaco', region: 'europe' },
  { id: 'marseille', name: 'Olympique de Marseille', stadium: 'Vélodrome', country: 'France', city: 'Marseille', region: 'europe' },
  { id: 'lyon', name: 'Olympique Lyonnais', stadium: 'Groupama Stadium', country: 'France', city: 'Lyon', region: 'europe' },
  { id: 'lille', name: 'LOSC Lille', stadium: 'Stade Pierre-Mauroy', country: 'France', city: 'Lille', region: 'europe' },
  { id: 'nice', name: 'OGC Nice', stadium: 'Allianz Riviera', country: 'France', city: 'Nice', region: 'europe' },
  // Netherlands
  { id: 'ajax', name: 'AFC Ajax', stadium: 'Johan Cruijff ArenA', country: 'Netherlands', city: 'Amsterdam', region: 'europe' },
  { id: 'psv', name: 'PSV Eindhoven', stadium: 'Philips Stadion', country: 'Netherlands', city: 'Eindhoven', region: 'europe' },
  { id: 'feyenoord', name: 'Feyenoord', stadium: 'De Kuip', country: 'Netherlands', city: 'Rotterdam', region: 'europe' },
  // Portugal
  { id: 'porto', name: 'FC Porto', stadium: 'Estádio do Dragão', country: 'Portugal', city: 'Porto', region: 'europe' },
  { id: 'benfica', name: 'SL Benfica', stadium: 'Estádio da Luz', country: 'Portugal', city: 'Lisbon', region: 'europe' },
  { id: 'sporting-cp', name: 'Sporting CP', stadium: 'Estádio José Alvalade', country: 'Portugal', city: 'Lisbon', region: 'europe' },
  // Belgium
  { id: 'anderlecht', name: 'RSC Anderlecht', stadium: 'Lotto Park', country: 'Belgium', city: 'Brussels', region: 'europe' },
  { id: 'club-brugge', name: 'Club Brugge', stadium: 'Jan Breydel Stadion', country: 'Belgium', city: 'Bruges', region: 'europe' },
  // Scotland
  { id: 'celtic', name: 'Celtic', stadium: 'Celtic Park', country: 'Scotland', city: 'Glasgow', region: 'europe' },
  { id: 'rangers', name: 'Rangers', stadium: 'Ibrox Stadium', country: 'Scotland', city: 'Glasgow', region: 'europe' },
  // Other
  { id: 'ajax-amsterdam', name: 'Ajax (Women)', stadium: 'Johan Cruijff ArenA', country: 'Netherlands', city: 'Amsterdam', region: 'europe' },
  { id: 'benfica-b', name: 'Benfica B', stadium: 'Estádio do Sport Lisboa e Benfica', country: 'Portugal', city: 'Lisbon', region: 'europe' },
  { id: 'brugge', name: 'Club Brugge', stadium: 'Jan Breydel Stadion', country: 'Belgium', city: 'Bruges', region: 'europe' },
  { id: 'red-bull-salzburg', name: 'Red Bull Salzburg', stadium: 'Red Bull Arena Salzburg', country: 'Austria', city: 'Salzburg', region: 'europe' },
  { id: 'shakhtar', name: 'Shakhtar Donetsk', stadium: 'Donbass Arena', country: 'Ukraine', city: 'Donetsk', region: 'europe' },
  { id: 'galatasaray', name: 'Galatasaray', stadium: 'RAMS Park', country: 'Turkey', city: 'Istanbul', region: 'europe' },
  { id: 'fenerbahce', name: 'Fenerbahçe', stadium: 'Şükrü Saracoğlu', country: 'Turkey', city: 'Istanbul', region: 'europe' },
  { id: 'anderlecht-2', name: 'Anderlecht B', stadium: 'Lotto Park', country: 'Belgium', city: 'Brussels', region: 'europe' },
  { id: 'crvena-zvezda', name: 'Red Star Belgrade', stadium: 'Marakana', country: 'Serbia', city: 'Belgrade', region: 'europe' },
  { id: 'dinamo-zagreb', name: 'Dinamo Zagreb', stadium: 'Stadion Maksimir', country: 'Croatia', city: 'Zagreb', region: 'europe' },
  { id: 'slavia-prague', name: 'Slavia Prague', stadium: 'Eden Arena', country: 'Czech Republic', city: 'Prague', region: 'europe' },
  { id: 'sporting-lisbon', name: 'Sporting Lisbon', stadium: 'Estádio José Alvalade', country: 'Portugal', city: 'Lisbon', region: 'europe' },
  { id: 'werder-bremen', name: 'Werder Bremen', stadium: 'Wohninvest Weserstadion', country: 'Germany', city: 'Bremen', region: 'europe' },
  { id: 'vfb-stuttgart', name: 'VfB Stuttgart', stadium: 'MHPArena', country: 'Germany', city: 'Stuttgart', region: 'europe' },
  { id: 'hamburger-sv', name: 'Hamburger SV', stadium: 'Volksparkstadion', country: 'Germany', city: 'Hamburg', region: 'europe' },
];

// Score categories used in rating JSON files
const SCORE_CATEGORIES = [
  { key: 'stadium_character', label: 'Stadium Character', emoji: '🏟', max: 10 },
  { key: 'clubhouse_concessions', label: 'Concessions', emoji: '🍺', max: 10 },
  { key: 'welcome_vibe', label: 'Welcome Vibe', emoji: '😊', max: 10 },
  { key: 'travel_value', label: 'Travel Value', emoji: '🚆', max: 10 },
];
