// Hawk Football Travels — Stadium & Club Data
// English clubs: Premier League down to Step 6 (National League North/South and Regional Divisions)
// Plus a European section

const ENGLISH_CLUBS = [
  // ── Premier League ──
  { id: 'arsenal', name: 'Arsenal', stadium: 'Emirates Stadium', tier: 1, league: 'Premier League', city: 'London', region: 'england', coordinates: { lat: 51.5549, lon: -0.1084 } },
  { id: 'aston-villa', name: 'Aston Villa', stadium: 'Villa Park', tier: 1, league: 'Premier League', city: 'Birmingham', region: 'england', coordinates: { lat: 52.5092, lon: -1.8848 } },
  { id: 'bournemouth', name: 'AFC Bournemouth', stadium: 'Vitality Stadium', tier: 1, league: 'Premier League', city: 'Bournemouth', region: 'england', coordinates: { lat: 50.7352, lon: -1.8382 } },
  { id: 'brentford', name: 'Brentford', stadium: 'Gtech Community Stadium', tier: 1, league: 'Premier League', city: 'London', region: 'england', coordinates: { lat: 51.4907, lon: -0.3026 } },
  { id: 'brighton', name: 'Brighton & Hove Albion', stadium: 'Amex Stadium', tier: 1, league: 'Premier League', city: 'Brighton', region: 'england', coordinates: { lat: 50.8610, lon: -0.0833 } },
  { id: 'chelsea', name: 'Chelsea', stadium: 'Stamford Bridge', tier: 1, league: 'Premier League', city: 'London', region: 'england', coordinates: { lat: 51.4816, lon: -0.1910 } },
  { id: 'coventry', name: 'Coventry City', stadium: 'Coventry Building Society Arena', tier: 1, league: 'Premier League', city: 'Coventry', region: 'england', coordinates: { lat: 52.4487, lon: -1.5003 } },
  { id: 'crystal-palace', name: 'Crystal Palace', stadium: 'Selhurst Park', tier: 1, league: 'Premier League', city: 'London', region: 'england', coordinates: { lat: 51.3983, lon: -0.0856 } },
  { id: 'everton', name: 'Everton', stadium: 'Goodison Park', tier: 1, league: 'Premier League', city: 'Liverpool', region: 'england', coordinates: { lat: 53.4386, lon: -2.9663 } },
  { id: 'fulham', name: 'Fulham', stadium: 'Craven Cottage', tier: 1, league: 'Premier League', city: 'London', region: 'england', coordinates: { lat: 51.4749, lon: -0.2217 } },
  { id: 'hull', name: 'Hull City', stadium: 'MKM Stadium', tier: 1, league: 'Premier League', city: 'Hull', region: 'england', coordinates: { lat: 53.7463, lon: -0.3680 } },
  { id: 'ipswich', name: 'Ipswich Town', stadium: 'Portman Road', tier: 1, league: 'Premier League', city: 'Ipswich', region: 'england', coordinates: { lat: 52.0548, lon: 1.1449 } },
  { id: 'leeds', name: 'Leeds United', stadium: 'Elland Road', tier: 1, league: 'Premier League', city: 'Leeds', region: 'england', coordinates: { lat: 53.7776, lon: -1.5724 } },
  { id: 'liverpool', name: 'Liverpool', stadium: 'Anfield', tier: 1, league: 'Premier League', city: 'Liverpool', region: 'england', coordinates: { lat: 53.4308, lon: -2.9608 } },
  { id: 'man-city', name: 'Manchester City', stadium: 'Etihad Stadium', tier: 1, league: 'Premier League', city: 'Manchester', region: 'england', coordinates: { lat: 53.4831, lon: -2.2004 } },
  { id: 'man-utd', name: 'Manchester United', stadium: 'Old Trafford', tier: 1, league: 'Premier League', city: 'Manchester', region: 'england', coordinates: { lat: 53.4631, lon: -2.2914 } },
  { id: 'newcastle', name: 'Newcastle United', stadium: "St. James' Park", tier: 1, league: 'Premier League', city: 'Newcastle', region: 'england' },
  { id: 'nottm-forest', name: 'Nottingham Forest', stadium: 'City Ground', tier: 1, league: 'Premier League', city: 'Nottingham', region: 'england' },
  { id: 'spurs', name: 'Tottenham Hotspur', stadium: 'Tottenham Hotspur Stadium', tier: 1, league: 'Premier League', city: 'London', region: 'england' },
  { id: 'sunderland', name: 'Sunderland', stadium: 'Stadium of Light', tier: 1, league: 'Premier League', city: 'Sunderland', region: 'england' },

  // ── Championship ──
  { id: 'birmingham', name: 'Birmingham City', stadium: 'St. Andrew\'s', tier: 2, league: 'Championship', city: 'Birmingham', region: 'england' },
  { id: 'blackburn', name: 'Blackburn Rovers', stadium: 'Ewood Park', tier: 2, league: 'Championship', city: 'Blackburn', region: 'england' },
  { id: 'bolton', name: 'Bolton Wanderers', stadium: 'Toughsheet Community Stadium', tier: 2, league: 'Championship', city: 'Bolton', region: 'england' },
  { id: 'bristol-city', name: 'Bristol City', stadium: 'Ashton Gate', tier: 2, league: 'Championship', city: 'Bristol', region: 'england' },
  { id: 'burnley', name: 'Burnley', stadium: 'Turf Moor', tier: 2, league: 'Championship', city: 'Burnley', region: 'england' },
  { id: 'cardiff', name: 'Cardiff City', stadium: 'Cardiff City Stadium', tier: 2, league: 'Championship', city: 'Cardiff', region: 'wales' },
  { id: 'charlton', name: 'Charlton Athletic', stadium: 'The Valley', tier: 2, league: 'Championship', city: 'London', region: 'england' },
  { id: 'derby', name: 'Derby County', stadium: 'Pride Park', tier: 2, league: 'Championship', city: 'Derby', region: 'england' },
  { id: 'lincoln', name: 'Lincoln City', stadium: 'LNER Stadium', tier: 2, league: 'Championship', city: 'Lincoln', region: 'england' },
  { id: 'middlesbrough', name: 'Middlesbrough', stadium: 'Riverside Stadium', tier: 2, league: 'Championship', city: 'Middlesbrough', region: 'england' },
  { id: 'millwall', name: 'Millwall', stadium: 'The Den', tier: 2, league: 'Championship', city: 'London', region: 'england' },
  { id: 'norwich', name: 'Norwich City', stadium: 'Carrow Road', tier: 2, league: 'Championship', city: 'Norwich', region: 'england' },
  { id: 'portsmouth', name: 'Portsmouth', stadium: 'Fratton Park', tier: 2, league: 'Championship', city: 'Portsmouth', region: 'england' },
  { id: 'preston', name: 'Preston North End', stadium: 'Deepdale', tier: 2, league: 'Championship', city: 'Preston', region: 'england' },
  { id: 'qpr', name: 'QPR', stadium: 'Loftus Road', tier: 2, league: 'Championship', city: 'London', region: 'england' },
  { id: 'sheffield-utd', name: 'Sheffield United', stadium: 'Bramall Lane', tier: 2, league: 'Championship', city: 'Sheffield', region: 'england' },
  { id: 'southampton', name: 'Southampton', stadium: "St. Mary's Stadium", tier: 2, league: 'Championship', city: 'Southampton', region: 'england' },
  { id: 'stoke', name: 'Stoke City', stadium: 'bet365 Stadium', tier: 2, league: 'Championship', city: 'Stoke-on-Trent', region: 'england' },
  { id: 'swansea', name: 'Swansea City', stadium: 'Swansea.com Stadium', tier: 2, league: 'Championship', city: 'Swansea', region: 'wales' },
  { id: 'watford', name: 'Watford', stadium: 'Vicarage Road', tier: 2, league: 'Championship', city: 'Watford', region: 'england' },
  { id: 'west-brom', name: 'West Bromwich Albion', stadium: 'The Hawthorns', tier: 2, league: 'Championship', city: 'West Bromwich', region: 'england' },
  { id: 'west-ham', name: 'West Ham United', stadium: 'London Stadium', tier: 2, league: 'Championship', city: 'London', region: 'england' },
  { id: 'wolves', name: 'Wolverhampton Wanderers', stadium: 'Molineux', tier: 2, league: 'Championship', city: 'Wolverhampton', region: 'england' },
  { id: 'wrexham', name: 'Wrexham', stadium: 'Racecourse Ground', tier: 2, league: 'Championship', city: 'Wrexham', region: 'wales' },

  // ── League One ──
  { id: 'afc-wimbledon', name: 'AFC Wimbledon', stadium: 'Plough Lane', tier: 3, league: 'League One', city: 'London', region: 'england' },
  { id: 'barnsley', name: 'Barnsley', stadium: 'Oakwell', tier: 3, league: 'League One', city: 'Barnsley', region: 'england' },
  { id: 'blackpool', name: 'Blackpool', stadium: 'Bloomfield Road', tier: 3, league: 'League One', city: 'Blackpool', region: 'england' },
  { id: 'bradford-city', name: 'Bradford City', stadium: 'Valley Parade', tier: 3, league: 'League One', city: 'Bradford', region: 'england' },
  { id: 'bromley', name: 'Bromley', stadium: 'Hayes Lane', tier: 3, league: 'League One', city: 'Bromley', region: 'england' },
  { id: 'burton', name: 'Burton Albion', stadium: 'Pirelli Stadium', tier: 3, league: 'League One', city: 'Burton upon Trent', region: 'england' },
  { id: 'cambridge', name: 'Cambridge United', stadium: 'Abbey Stadium', tier: 3, league: 'League One', city: 'Cambridge', region: 'england' },
  { id: 'doncaster', name: 'Doncaster Rovers', stadium: 'Eco-Power Stadium', tier: 3, league: 'League One', city: 'Doncaster', region: 'england' },
  { id: 'huddersfield', name: 'Huddersfield Town', stadium: 'John Smith\'s Stadium', tier: 3, league: 'League One', city: 'Huddersfield', region: 'england' },
  { id: 'leicester', name: 'Leicester City', stadium: 'King Power Stadium', tier: 3, league: 'League One', city: 'Leicester', region: 'england' },
  { id: 'leyton-orient', name: 'Leyton Orient', stadium: 'Brisbane Road', tier: 3, league: 'League One', city: 'London', region: 'england' },
  { id: 'luton', name: 'Luton Town', stadium: 'Kenilworth Road', tier: 3, league: 'League One', city: 'Luton', region: 'england' },
  { id: 'mansfield', name: 'Mansfield Town', stadium: 'One Call Stadium', tier: 3, league: 'League One', city: 'Mansfield', region: 'england' },
  { id: 'mk-dons', name: 'MK Dons', stadium: 'Stadium MK', tier: 3, league: 'League One', city: 'Milton Keynes', region: 'england' },
  { id: 'notts-county', name: 'Notts County', stadium: 'Meadow Lane', tier: 3, league: 'League One', city: 'Nottingham', region: 'england' },
  { id: 'oxford', name: 'Oxford United', stadium: "Kassam Stadium", tier: 3, league: 'League One', city: 'Oxford', region: 'england' },
  { id: 'peterborough', name: 'Peterborough United', stadium: 'London Road', tier: 3, league: 'League One', city: 'Peterborough', region: 'england' },
  { id: 'plymouth', name: 'Plymouth Argyle', stadium: 'Home Park', tier: 3, league: 'League One', city: 'Plymouth', region: 'england' },
  { id: 'reading', name: 'Reading', stadium: 'Select Car Leasing Stadium', tier: 3, league: 'League One', city: 'Reading', region: 'england' },
  { id: 'sheffield-wed', name: 'Sheffield Wednesday', stadium: 'Hillsborough', tier: 3, league: 'League One', city: 'Sheffield', region: 'england' },
  { id: 'stevenage', name: 'Stevenage', stadium: 'Lamex Stadium', tier: 3, league: 'League One', city: 'Stevenage', region: 'england' },
  { id: 'stockport', name: 'Stockport County', stadium: 'Edgeley Park', tier: 3, league: 'League One', city: 'Stockport', region: 'england' },
  { id: 'wigan', name: 'Wigan Athletic', stadium: 'DW Stadium', tier: 3, league: 'League One', city: 'Wigan', region: 'england' },
  { id: 'wycombe', name: 'Wycombe Wanderers', stadium: 'Adams Park', tier: 3, league: 'League One', city: 'High Wycombe', region: 'england' },

  // ── League Two ──
  { id: 'walsall', name: 'Walsall', stadium: 'Poundland Bescot Stadium', tier: 4, league: 'League Two', city: 'Walsall', region: 'england' },
  { id: 'newport', name: 'Newport County', stadium: 'Rodney Parade', tier: 4, league: 'League Two', city: 'Newport', region: 'wales' },
  { id: 'barnet', name: 'Barnet', stadium: 'The Hive London', tier: 4, league: 'League Two', city: 'London', region: 'england' },
  { id: 'oldham', name: 'Oldham Athletic', stadium: 'Boundary Park', tier: 4, league: 'League Two', city: 'Oldham', region: 'england' },
  { id: 'tranmere', name: 'Tranmere Rovers', stadium: 'Prenton Park', tier: 4, league: 'League Two', city: 'Birkenhead', region: 'england' },
  { id: 'york-city-l2', name: 'York City', stadium: 'LNER Community Stadium', tier: 4, league: 'League Two', city: 'York', region: 'england' },
  { id: 'cheltenham', name: 'Cheltenham Town', stadium: 'Jonny-Rocks Stadium', tier: 4, league: 'League Two', city: 'Cheltenham', region: 'england' },
  { id: 'crewe', name: 'Crewe Alexandra', stadium: 'Alexandra Stadium', tier: 4, league: 'League Two', city: 'Crewe', region: 'england' },
  { id: 'fleetwood', name: 'Fleetwood Town', stadium: 'Highbury Stadium', tier: 4, league: 'League Two', city: 'Fleetwood', region: 'england' },
  { id: 'grimsby', name: 'Grimsby Town', stadium: 'Blundell Park', tier: 4, league: 'League Two', city: 'Grimsby', region: 'england' },
  { id: 'colchester', name: 'Colchester United', stadium: 'JobServe Community Stadium', tier: 4, league: 'League Two', city: 'Colchester', region: 'england' },
  { id: 'accrington', name: 'Accrington Stanley', stadium: 'Crown Ground', tier: 4, league: 'League Two', city: 'Accrington', region: 'england' },
  { id: 'northampton', name: 'Northampton Town', stadium: 'Sixfields Stadium', tier: 4, league: 'League Two', city: 'Northampton', region: 'england' },
  { id: 'swindon', name: 'Swindon Town', stadium: 'County Ground', tier: 4, league: 'League Two', city: 'Swindon', region: 'england' },
  { id: 'bristol-rovers', name: 'Bristol Rovers', stadium: 'Memorial Stadium', tier: 4, league: 'League Two', city: 'Bristol', region: 'england' },
  { id: 'rotherham', name: 'Rotherham United', stadium: 'New York Stadium', tier: 4, league: 'League Two', city: 'Rotherham', region: 'england' },
  { id: 'chesterfield', name: 'Chesterfield', stadium: 'Technique Stadium', tier: 4, league: 'League Two', city: 'Chesterfield', region: 'england' },
  { id: 'crawley', name: 'Crawley Town', stadium: 'Broadfield Stadium', tier: 4, league: 'League Two', city: 'Crawley', region: 'england' },
  { id: 'exeter', name: 'Exeter City', stadium: 'St James Park', tier: 4, league: 'League Two', city: 'Exeter', region: 'england' },
  { id: 'salford', name: 'Salford City', stadium: 'Peninsula Stadium', tier: 4, league: 'League Two', city: 'Salford', region: 'england' },
  { id: 'port-vale', name: 'Port Vale', stadium: 'Vale Park', tier: 4, league: 'League Two', city: 'Burslem', region: 'england' },
  { id: 'shrewsbury', name: 'Shrewsbury Town', stadium: 'New Meadow', tier: 4, league: 'League Two', city: 'Shrewsbury', region: 'england' },
  { id: 'gillingham', name: 'Gillingham', stadium: 'MEMS Priestfield Stadium', tier: 4, league: 'League Two', city: 'Gillingham', region: 'england' },
  { id: 'rochdale', name: 'Rochdale', stadium: 'Crown Oil Arena', tier: 4, league: 'League Two', city: 'Rochdale', region: 'england' },

  // ── National League (Step 5) ──
  { id: 'afc-fylde', name: 'AFC Fylde', stadium: 'Mill Farm', tier: 5, league: 'National League', city: 'Wesham', region: 'england' },
  { id: 'aldershot', name: 'Aldershot Town', stadium: 'EBB Stadium', tier: 5, league: 'National League', city: 'Aldershot', region: 'england' },
  { id: 'altrincham', name: 'Altrincham', stadium: 'J.Davidson Stadium', tier: 5, league: 'National League', city: 'Altrincham', region: 'england' },
  { id: 'barrow-nl', name: 'Barrow', stadium: 'Holker Street', tier: 5, league: 'National League', city: 'Barrow-in-Furness', region: 'england' },
  { id: 'boreham-wood', name: 'Boreham Wood', stadium: 'Meadow Park', tier: 5, league: 'National League', city: 'Boreham Wood', region: 'england' },
  { id: 'boston-united', name: 'Boston United', stadium: 'Jakemans Community Stadium', tier: 5, league: 'National League', city: 'Boston', region: 'england' },
  { id: 'carlisle-nl', name: 'Carlisle United', stadium: 'Brunton Park', tier: 5, league: 'National League', city: 'Carlisle', region: 'england' },
  { id: 'eastleigh', name: 'Eastleigh', stadium: 'Silverlake Stadium', tier: 5, league: 'National League', city: 'Eastleigh', region: 'england' },
  { id: 'fc-halifax', name: 'FC Halifax Town', stadium: 'The Shay', tier: 5, league: 'National League', city: 'Halifax', region: 'england' },
  { id: 'forest-green', name: 'Forest Green Rovers', stadium: 'The New Lawn', tier: 5, league: 'National League', city: 'Nailsworth', region: 'england' },
  { id: 'gateshead', name: 'Gateshead', stadium: 'Gateshead International Stadium', tier: 5, league: 'National League', city: 'Gateshead', region: 'england' },
  { id: 'harrogate-nl', name: 'Harrogate Town', stadium: 'EnviroVent Stadium', tier: 5, league: 'National League', city: 'Harrogate', region: 'england' },
  { id: 'hartlepool', name: 'Hartlepool United', stadium: 'Victoria Park', tier: 5, league: 'National League', city: 'Hartlepool', region: 'england' },
  { id: 'hornchurch-nl', name: 'Hornchurch', stadium: 'Hornchurch Stadium', tier: 5, league: 'National League', city: 'Hornchurch', region: 'england' },
  { id: 'kidderminster', name: 'Kidderminster Harriers', stadium: 'Aggborough Stadium', tier: 5, league: 'National League', city: 'Kidderminster', region: 'england' },
  { id: 'scunthorpe', name: 'Scunthorpe United', stadium: 'Glanford Park', tier: 5, league: 'National League', city: 'Scunthorpe', region: 'england' },
  { id: 'solihull', name: 'Solihull Moors', stadium: 'ARMCO Arena', tier: 5, league: 'National League', city: 'Solihull', region: 'england' },
  { id: 'southend', name: 'Southend United', stadium: 'Roots Hall', tier: 5, league: 'National League', city: 'Southend-on-Sea', region: 'england' },
  { id: 'sutton', name: 'Sutton United', stadium: 'Gander Green Lane', tier: 5, league: 'National League', city: 'Sutton', region: 'england' },
  { id: 'tamworth', name: 'Tamworth', stadium: 'The Lamb Ground', tier: 5, league: 'National League', city: 'Tamworth', region: 'england' },
  { id: 'wealdstone', name: 'Wealdstone', stadium: 'Grosvenor Vale', tier: 5, league: 'National League', city: 'Wealdstone', region: 'england' },
  { id: 'woking', name: 'Woking', stadium: 'Kingfield Stadium', tier: 5, league: 'National League', city: 'Woking', region: 'england' },
  { id: 'worthing-nl', name: 'Worthing', stadium: 'Woodside Road', tier: 5, league: 'National League', city: 'Worthing', region: 'england' },
  { id: 'yeovil', name: 'Yeovil Town', stadium: 'Huish Park', tier: 5, league: 'National League', city: 'Yeovil', region: 'england' },

  // ── National League North (Step 6) — 2026-27 Season ──
  { id: 'afc-telford', name: 'AFC Telford United', stadium: 'New Bucks Head', tier: 6, league: 'National League North', city: 'Telford', region: 'england' },
  { id: 'bedford-town', name: 'Bedford Town', stadium: 'The Eyrie', tier: 6, league: 'National League North', city: 'Bedford', region: 'england' },
  { id: 'brackley', name: 'Brackley Town', stadium: 'St James Park', tier: 6, league: 'National League North', city: 'Brackley', region: 'england' },
  { id: 'buxton', name: 'Buxton', stadium: 'Silverlands', tier: 6, league: 'National League North', city: 'Buxton', region: 'england' },
  { id: 'chester', name: 'Chester', stadium: 'Deva Stadium', tier: 6, league: 'National League North', city: 'Chester', region: 'england' },
  { id: 'chorley', name: 'Chorley', stadium: 'Victory Park', tier: 6, league: 'National League North', city: 'Chorley', region: 'england' },
  { id: 'darlington', name: 'Darlington', stadium: 'Blackwell Meadows', tier: 6, league: 'National League North', city: 'Darlington', region: 'england' },
  { id: 'harborough-town', name: 'Harborough Town', stadium: 'Bowdens Park', tier: 6, league: 'National League North', city: 'Market Harborough', region: 'england' },
  { id: 'hebburn-town', name: 'Hebburn Town', stadium: 'Hebburn Sports & Social Ground', tier: 6, league: 'National League North', city: 'Hebburn', region: 'england' },
  { id: 'hednesford-town', name: 'Hednesford Town', stadium: 'Keys Park', tier: 6, league: 'National League North', city: 'Hednesford', region: 'england' },
  { id: 'hereford', name: 'Hereford', stadium: 'Edgar Street', tier: 6, league: 'National League North', city: 'Hereford', region: 'england' },
  { id: 'kings-lynn', name: 'King\'s Lynn Town', stadium: 'The Walks', tier: 6, league: 'National League North', city: 'King\'s Lynn', region: 'england' },
  { id: 'macclesfield', name: 'Macclesfield', stadium: 'Moss Rose', tier: 6, league: 'National League North', city: 'Macclesfield', region: 'england' },
  { id: 'marine', name: 'Marine', stadium: 'Marine Travel Arena', tier: 6, league: 'National League North', city: 'Crosby', region: 'england' },
  { id: 'merthyr-town', name: 'Merthyr Town', stadium: 'Penydarren Park', tier: 6, league: 'National League North', city: 'Merthyr Tydfil', region: 'wales' },
  { id: 'morecambe-nln', name: 'Morecambe', stadium: 'Mazuma Mobile Stadium', tier: 6, league: 'National League North', city: 'Morecambe', region: 'england' },
  { id: 'oxford-city', name: 'Oxford City', stadium: 'Court Place Farm', tier: 6, league: 'National League North', city: 'Oxford', region: 'england' },
  { id: 'radcliffe', name: 'Radcliffe', stadium: 'Neuven Stadium', tier: 6, league: 'National League North', city: 'Radcliffe', region: 'england' },
  { id: 'scarborough-athletic', name: 'Scarborough Athletic', stadium: 'Flamingo Land Stadium', tier: 6, league: 'National League North', city: 'Scarborough', region: 'england' },
  { id: 'south-shields', name: 'South Shields', stadium: '1st Cloud Arena', tier: 6, league: 'National League North', city: 'South Shields', region: 'england' },
  { id: 'southport', name: 'Southport', stadium: 'Merseyrail Community Stadium', tier: 6, league: 'National League North', city: 'Southport', region: 'england' },
  { id: 'spalding-united', name: 'Spalding United', stadium: 'Sir Halley Stewart Playing Field', tier: 6, league: 'National League North', city: 'Spalding', region: 'england' },
  { id: 'spennymoor', name: 'Spennymoor Town', stadium: 'Brewery Field', tier: 6, league: 'National League North', city: 'Spennymoor', region: 'england' },
  { id: 'worksop-town', name: 'Worksop Town', stadium: 'Sandy Lane', tier: 6, league: 'National League North', city: 'Worksop', region: 'england' },

  // ── National League South (Step 6) — 2026-27 Season ──
  { id: 'afc-totton', name: 'AFC Totton', stadium: 'Testwood Park', tier: 6, league: 'National League South', city: 'Totton', region: 'england' },
  { id: 'billericay-town', name: 'Billericay Town', stadium: 'New Lodge', tier: 6, league: 'National League South', city: 'Billericay', region: 'england' },
  { id: 'braintree-town', name: 'Braintree Town', stadium: 'The Iron Recreation Ground', tier: 6, league: 'National League South', city: 'Braintree', region: 'england' },
  { id: 'chelmsford', name: 'Chelmsford City', stadium: 'Melbourne Stadium', tier: 6, league: 'National League South', city: 'Chelmsford', region: 'england' },
  { id: 'chesham-united', name: 'Chesham United', stadium: 'The Meadow', tier: 6, league: 'National League South', city: 'Chesham', region: 'england' },
  { id: 'dagenham', name: 'Dagenham & Redbridge', stadium: 'Victoria Road', tier: 6, league: 'National League South', city: 'Dagenham', region: 'england' },
  { id: 'dorking', name: 'Dorking Wanderers', stadium: 'Meadowbank', tier: 6, league: 'National League South', city: 'Dorking', region: 'england' },
  { id: 'dover', name: 'Dover Athletic', stadium: 'Crabble Athletic Ground', tier: 6, league: 'National League South', city: 'Dover', region: 'england' },
  { id: 'ebbsfleet', name: 'Ebbsfleet United', stadium: 'Stonebridge Road', tier: 6, league: 'National League South', city: 'Northfleet', region: 'england' },
  { id: 'farnborough', name: 'Farnborough', stadium: 'Rushmoor Stadium', tier: 6, league: 'National League South', city: 'Farnborough', region: 'england' },
  { id: 'farnham-town', name: 'Farnham Town', stadium: 'Badshot Lea', tier: 6, league: 'National League South', city: 'Farnham', region: 'england' },
  { id: 'folkestone-invicta', name: 'Folkestone Invicta', stadium: 'Cheriton Road', tier: 6, league: 'National League South', city: 'Folkestone', region: 'england' },
  { id: 'hampton', name: 'Hampton & Richmond Borough', stadium: 'Beveree Stadium', tier: 6, league: 'National League South', city: 'Hampton', region: 'england' },
  { id: 'hemel', name: 'Hemel Hempstead Town', stadium: 'Vauxhall Road', tier: 6, league: 'National League South', city: 'Hemel Hempstead', region: 'england' },
  { id: 'horsham', name: 'Horsham', stadium: 'Gorings Mead', tier: 6, league: 'National League South', city: 'Horsham', region: 'england' },
  { id: 'maidenhead', name: 'Maidenhead United', stadium: 'York Road', tier: 6, league: 'National League South', city: 'Maidenhead', region: 'england' },
  { id: 'maidstone-nls', name: 'Maidstone United', stadium: 'Gallagher Stadium', tier: 6, league: 'National League South', city: 'Maidstone', region: 'england' },
  { id: 'salisbury', name: 'Salisbury', stadium: 'Raymond McEnhill Stadium', tier: 6, league: 'National League South', city: 'Salisbury', region: 'england' },
  { id: 'slough', name: 'Slough Town', stadium: 'Arbour Park', tier: 6, league: 'National League South', city: 'Slough', region: 'england' },
  { id: 'tonbridge', name: 'Tonbridge Angels', stadium: 'Longmead Stadium', tier: 6, league: 'National League South', city: 'Tonbridge', region: 'england' },
  { id: 'torquay-nls', name: 'Torquay United', stadium: 'Plainmoor', tier: 6, league: 'National League South', city: 'Torquay', region: 'england' },
  { id: 'truro', name: 'Truro City', stadium: 'Treyew Road', tier: 6, league: 'National League South', city: 'Truro', region: 'england' },
  { id: 'walton-hersham', name: 'Walton & Hersham', stadium: 'Stompond Lane', tier: 6, league: 'National League South', city: 'Walton-on-Thames', region: 'england' },
  { id: 'weston', name: 'Weston-super-Mare', stadium: 'Woodspring Stadium', tier: 6, league: 'National League South', city: 'Weston-super-Mare', region: 'england' },
];

// Groundhopping App Scoring System - 100 Point Scale (10 Categories × 10 Points)
const SCORE_CATEGORIES = [
  { key: 'sightlines_view', label: 'Sightlines & View', emoji: '👀', max: 10, description: 'Sightlines, stand elevation, pitch proximity, pillar obstruction' },
  { key: 'architecture_character', label: 'Architecture & Character', emoji: '🏛️', max: 10, description: 'Historic stands, terracing, unique quirks, ground soul' },
  { key: 'cover_pitch', label: 'Cover & Pitch', emoji: '🌧️', max: 10, description: 'Weather shelter, roof coverage, wind protection, pitch condition' },
  { key: 'happy_wife_happy_life', label: 'Happy Wife, Happy Life', emoji: '👫', max: 10, description: 'Local area safety, comfort, cafes, shopping, appeal for non-attending spouse' },
  { key: 'inground_bars_concourses', label: 'In-Ground Bars & Concourses', emoji: '🍺', max: 10, description: 'Concourse space, bar speed, pint options, pricing, inside fan zones' },
  { key: 'prematch_local_scene', label: 'Pre-Match Local Scene', emoji: '🍻', max: 10, description: 'Nearby craft breweries, local pubs, pre-turnstile food options' },
  { key: 'atmosphere_fan_noise', label: 'Atmosphere & Fan Noise', emoji: '📢', max: 10, description: 'Chanting, home/away noise levels, match anthems, general vibe' },
  { key: 'club_welcome_hospitality', label: 'Club Welcome & Hospitality', emoji: '🤝', max: 10, description: 'Gate staff warmth, volunteer friendliness, physical programmes/team sheets' },
  { key: 'travel_transit_logistics', label: 'Travel & Transit Logistics', emoji: '🚆', max: 10, description: 'Station train frequency, bus/Uber ease, highway access, parking' },
  { key: 'ticket_admission_value', label: 'Ticket & Admission Value', emoji: '🎫', max: 10, description: 'Ticket price relative to quality of football and overall matchday experience' },
];
